# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add k "kubecolor"
abbr --add ksys "kubecolor --namespace=kube-system"
abbr --add ka "kubecolor apply --recursive -f"
abbr --add ksysa "kubecolor --namespace=kube-system apply --recursive -f"
abbr --add kak "kubecolor apply -k"
abbr --add kk "kubecolor kustomize"
abbr --add kex "kubecolor exec -i -t"
abbr --add ksysex "kubecolor --namespace=kube-system exec -i -t"
abbr --add klo "kubecolor logs -f"
abbr --add ksyslo "kubecolor --namespace=kube-system logs -f"
abbr --add klop "kubecolor logs -f -p"
abbr --add ksyslop "kubecolor --namespace=kube-system logs -f -p"
abbr --add kp "kubecolor proxy"
abbr --add kpf "kubecolor port-forward"
abbr --add kg "kubecolor get"
abbr --add ksysg "kubecolor --namespace=kube-system get"
abbr --add kd "kubecolor describe"
abbr --add ksysd "kubecolor --namespace=kube-system describe"
abbr --add krm "kubecolor delete"
abbr --add ksysrm "kubecolor --namespace=kube-system delete"
abbr --add krun "kubecolor run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubecolor --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kgpo "kubecolor get pods"
abbr --add ksysgpo "kubecolor --namespace=kube-system get pods"
abbr --add kdpo "kubecolor describe pods"
abbr --add ksysdpo "kubecolor --namespace=kube-system describe pods"
abbr --add krmpo "kubecolor delete pods"
abbr --add ksysrmpo "kubecolor --namespace=kube-system delete pods"
abbr --add kgdep "kubecolor get deployment"
abbr --add ksysgdep "kubecolor --namespace=kube-system get deployment"
abbr --add kddep "kubecolor describe deployment"
abbr --add ksysddep "kubecolor --namespace=kube-system describe deployment"
abbr --add krmdep "kubecolor delete deployment"
abbr --add ksysrmdep "kubecolor --namespace=kube-system delete deployment"
abbr --add kgsts "kubecolor get statefulset"
abbr --add ksysgsts "kubecolor --namespace=kube-system get statefulset"
abbr --add kdsts "kubecolor describe statefulset"
abbr --add ksysdsts "kubecolor --namespace=kube-system describe statefulset"
abbr --add krmsts "kubecolor delete statefulset"
abbr --add ksysrmsts "kubecolor --namespace=kube-system delete statefulset"
abbr --add kgsvc "kubecolor get service"
abbr --add ksysgsvc "kubecolor --namespace=kube-system get service"
abbr --add kdsvc "kubecolor describe service"
abbr --add ksysdsvc "kubecolor --namespace=kube-system describe service"
abbr --add krmsvc "kubecolor delete service"
abbr --add ksysrmsvc "kubecolor --namespace=kube-system delete service"
abbr --add kging "kubecolor get ingress"
abbr --add ksysging "kubecolor --namespace=kube-system get ingress"
abbr --add kding "kubecolor describe ingress"
abbr --add ksysding "kubecolor --namespace=kube-system describe ingress"
abbr --add krming "kubecolor delete ingress"
abbr --add ksysrming "kubecolor --namespace=kube-system delete ingress"
abbr --add kgcm "kubecolor get configmap"
abbr --add ksysgcm "kubecolor --namespace=kube-system get configmap"
abbr --add kdcm "kubecolor describe configmap"
abbr --add ksysdcm "kubecolor --namespace=kube-system describe configmap"
abbr --add krmcm "kubecolor delete configmap"
abbr --add ksysrmcm "kubecolor --namespace=kube-system delete configmap"
abbr --add kgsec "kubecolor get secret"
abbr --add ksysgsec "kubecolor --namespace=kube-system get secret"
abbr --add kdsec "kubecolor describe secret"
abbr --add ksysdsec "kubecolor --namespace=kube-system describe secret"
abbr --add krmsec "kubecolor delete secret"
abbr --add ksysrmsec "kubecolor --namespace=kube-system delete secret"
abbr --add kgno "kubecolor get nodes"
abbr --add kdno "kubecolor describe nodes"
abbr --add kgns "kubecolor get namespaces"
abbr --add kdns "kubecolor describe namespaces"
abbr --add krmns "kubecolor delete namespaces"
abbr --add kgoyaml "kubecolor get -o=yaml"
abbr --add ksysgoyaml "kubecolor --namespace=kube-system get -o=yaml"
abbr --add kgpooyaml "kubecolor get pods -o=yaml"
abbr --add ksysgpooyaml "kubecolor --namespace=kube-system get pods -o=yaml"
abbr --add kgdepoyaml "kubecolor get deployment -o=yaml"
abbr --add ksysgdepoyaml "kubecolor --namespace=kube-system get deployment -o=yaml"
abbr --add kgstsoyaml "kubecolor get statefulset -o=yaml"
abbr --add ksysgstsoyaml "kubecolor --namespace=kube-system get statefulset -o=yaml"
abbr --add kgsvcoyaml "kubecolor get service -o=yaml"
abbr --add ksysgsvcoyaml "kubecolor --namespace=kube-system get service -o=yaml"
abbr --add kgingoyaml "kubecolor get ingress -o=yaml"
abbr --add ksysgingoyaml "kubecolor --namespace=kube-system get ingress -o=yaml"
abbr --add kgcmoyaml "kubecolor get configmap -o=yaml"
abbr --add ksysgcmoyaml "kubecolor --namespace=kube-system get configmap -o=yaml"
abbr --add kgsecoyaml "kubecolor get secret -o=yaml"
abbr --add ksysgsecoyaml "kubecolor --namespace=kube-system get secret -o=yaml"
abbr --add kgnooyaml "kubecolor get nodes -o=yaml"
abbr --add kgnsoyaml "kubecolor get namespaces -o=yaml"
abbr --add kgowide "kubecolor get -o=wide"
abbr --add ksysgowide "kubecolor --namespace=kube-system get -o=wide"
abbr --add kgpoowide "kubecolor get pods -o=wide"
abbr --add ksysgpoowide "kubecolor --namespace=kube-system get pods -o=wide"
abbr --add kgdepowide "kubecolor get deployment -o=wide"
abbr --add ksysgdepowide "kubecolor --namespace=kube-system get deployment -o=wide"
abbr --add kgstsowide "kubecolor get statefulset -o=wide"
abbr --add ksysgstsowide "kubecolor --namespace=kube-system get statefulset -o=wide"
abbr --add kgsvcowide "kubecolor get service -o=wide"
abbr --add ksysgsvcowide "kubecolor --namespace=kube-system get service -o=wide"
abbr --add kgingowide "kubecolor get ingress -o=wide"
abbr --add ksysgingowide "kubecolor --namespace=kube-system get ingress -o=wide"
abbr --add kgcmowide "kubecolor get configmap -o=wide"
abbr --add ksysgcmowide "kubecolor --namespace=kube-system get configmap -o=wide"
abbr --add kgsecowide "kubecolor get secret -o=wide"
abbr --add ksysgsecowide "kubecolor --namespace=kube-system get secret -o=wide"
abbr --add kgnoowide "kubecolor get nodes -o=wide"
abbr --add kgnsowide "kubecolor get namespaces -o=wide"
abbr --add kgojson "kubecolor get -o=json"
abbr --add ksysgojson "kubecolor --namespace=kube-system get -o=json"
abbr --add kgpoojson "kubecolor get pods -o=json"
abbr --add ksysgpoojson "kubecolor --namespace=kube-system get pods -o=json"
abbr --add kgdepojson "kubecolor get deployment -o=json"
abbr --add ksysgdepojson "kubecolor --namespace=kube-system get deployment -o=json"
abbr --add kgstsojson "kubecolor get statefulset -o=json"
abbr --add ksysgstsojson "kubecolor --namespace=kube-system get statefulset -o=json"
abbr --add kgsvcojson "kubecolor get service -o=json"
abbr --add ksysgsvcojson "kubecolor --namespace=kube-system get service -o=json"
abbr --add kgingojson "kubecolor get ingress -o=json"
abbr --add ksysgingojson "kubecolor --namespace=kube-system get ingress -o=json"
abbr --add kgcmojson "kubecolor get configmap -o=json"
abbr --add ksysgcmojson "kubecolor --namespace=kube-system get configmap -o=json"
abbr --add kgsecojson "kubecolor get secret -o=json"
abbr --add ksysgsecojson "kubecolor --namespace=kube-system get secret -o=json"
abbr --add kgnoojson "kubecolor get nodes -o=json"
abbr --add kgnsojson "kubecolor get namespaces -o=json"
abbr --add kgall "kubecolor get --all-namespaces"
abbr --add kdall "kubecolor describe --all-namespaces"
abbr --add kgpoall "kubecolor get pods --all-namespaces"
abbr --add kdpoall "kubecolor describe pods --all-namespaces"
abbr --add kgdepall "kubecolor get deployment --all-namespaces"
abbr --add kddepall "kubecolor describe deployment --all-namespaces"
abbr --add kgstsall "kubecolor get statefulset --all-namespaces"
abbr --add kdstsall "kubecolor describe statefulset --all-namespaces"
abbr --add kgsvcall "kubecolor get service --all-namespaces"
abbr --add kdsvcall "kubecolor describe service --all-namespaces"
abbr --add kgingall "kubecolor get ingress --all-namespaces"
abbr --add kdingall "kubecolor describe ingress --all-namespaces"
abbr --add kgcmall "kubecolor get configmap --all-namespaces"
abbr --add kdcmall "kubecolor describe configmap --all-namespaces"
abbr --add kgsecall "kubecolor get secret --all-namespaces"
abbr --add kdsecall "kubecolor describe secret --all-namespaces"
abbr --add kgsl "kubecolor get --show-labels"
abbr --add ksysgsl "kubecolor --namespace=kube-system get --show-labels"
abbr --add kgposl "kubecolor get pods --show-labels"
abbr --add ksysgposl "kubecolor --namespace=kube-system get pods --show-labels"
abbr --add kgdepsl "kubecolor get deployment --show-labels"
abbr --add ksysgdepsl "kubecolor --namespace=kube-system get deployment --show-labels"
abbr --add kgstssl "kubecolor get statefulset --show-labels"
abbr --add ksysgstssl "kubecolor --namespace=kube-system get statefulset --show-labels"
abbr --add kgsvcsl "kubecolor get service --show-labels"
abbr --add ksysgsvcsl "kubecolor --namespace=kube-system get service --show-labels"
abbr --add kgingsl "kubecolor get ingress --show-labels"
abbr --add ksysgingsl "kubecolor --namespace=kube-system get ingress --show-labels"
abbr --add kgcmsl "kubecolor get configmap --show-labels"
abbr --add ksysgcmsl "kubecolor --namespace=kube-system get configmap --show-labels"
abbr --add kgsecsl "kubecolor get secret --show-labels"
abbr --add ksysgsecsl "kubecolor --namespace=kube-system get secret --show-labels"
abbr --add kgnosl "kubecolor get nodes --show-labels"
abbr --add kgnssl "kubecolor get namespaces --show-labels"
abbr --add krmall "kubecolor delete --all"
abbr --add ksysrmall "kubecolor --namespace=kube-system delete --all"
abbr --add krmpoall "kubecolor delete pods --all"
abbr --add ksysrmpoall "kubecolor --namespace=kube-system delete pods --all"
abbr --add krmdepall "kubecolor delete deployment --all"
abbr --add ksysrmdepall "kubecolor --namespace=kube-system delete deployment --all"
abbr --add krmstsall "kubecolor delete statefulset --all"
abbr --add ksysrmstsall "kubecolor --namespace=kube-system delete statefulset --all"
abbr --add krmsvcall "kubecolor delete service --all"
abbr --add ksysrmsvcall "kubecolor --namespace=kube-system delete service --all"
abbr --add krmingall "kubecolor delete ingress --all"
abbr --add ksysrmingall "kubecolor --namespace=kube-system delete ingress --all"
abbr --add krmcmall "kubecolor delete configmap --all"
abbr --add ksysrmcmall "kubecolor --namespace=kube-system delete configmap --all"
abbr --add krmsecall "kubecolor delete secret --all"
abbr --add ksysrmsecall "kubecolor --namespace=kube-system delete secret --all"
abbr --add krmnsall "kubecolor delete namespaces --all"
abbr --add kgw "kubecolor get --watch"
abbr --add ksysgw "kubecolor --namespace=kube-system get --watch"
abbr --add kgpow "kubecolor get pods --watch"
abbr --add ksysgpow "kubecolor --namespace=kube-system get pods --watch"
abbr --add kgdepw "kubecolor get deployment --watch"
abbr --add ksysgdepw "kubecolor --namespace=kube-system get deployment --watch"
abbr --add kgstsw "kubecolor get statefulset --watch"
abbr --add ksysgstsw "kubecolor --namespace=kube-system get statefulset --watch"
abbr --add kgsvcw "kubecolor get service --watch"
abbr --add ksysgsvcw "kubecolor --namespace=kube-system get service --watch"
abbr --add kgingw "kubecolor get ingress --watch"
abbr --add ksysgingw "kubecolor --namespace=kube-system get ingress --watch"
abbr --add kgcmw "kubecolor get configmap --watch"
abbr --add ksysgcmw "kubecolor --namespace=kube-system get configmap --watch"
abbr --add kgsecw "kubecolor get secret --watch"
abbr --add ksysgsecw "kubecolor --namespace=kube-system get secret --watch"
abbr --add kgnow "kubecolor get nodes --watch"
abbr --add kgnsw "kubecolor get namespaces --watch"
abbr --add kgoyamlall "kubecolor get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "kubecolor get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "kubecolor get deployment -o=yaml --all-namespaces"
abbr --add kgstsoyamlall "kubecolor get statefulset -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "kubecolor get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "kubecolor get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "kubecolor get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "kubecolor get secret -o=yaml --all-namespaces"
abbr --add kgalloyaml "kubecolor get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "kubecolor get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "kubecolor get deployment --all-namespaces -o=yaml"
abbr --add kgstsalloyaml "kubecolor get statefulset --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "kubecolor get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "kubecolor get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "kubecolor get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "kubecolor get secret --all-namespaces -o=yaml"
abbr --add kgowideall "kubecolor get -o=wide --all-namespaces"
abbr --add kgpoowideall "kubecolor get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "kubecolor get deployment -o=wide --all-namespaces"
abbr --add kgstsowideall "kubecolor get statefulset -o=wide --all-namespaces"
abbr --add kgsvcowideall "kubecolor get service -o=wide --all-namespaces"
abbr --add kgingowideall "kubecolor get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "kubecolor get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "kubecolor get secret -o=wide --all-namespaces"
abbr --add kgallowide "kubecolor get --all-namespaces -o=wide"
abbr --add kgpoallowide "kubecolor get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "kubecolor get deployment --all-namespaces -o=wide"
abbr --add kgstsallowide "kubecolor get statefulset --all-namespaces -o=wide"
abbr --add kgsvcallowide "kubecolor get service --all-namespaces -o=wide"
abbr --add kgingallowide "kubecolor get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "kubecolor get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "kubecolor get secret --all-namespaces -o=wide"
abbr --add kgowidesl "kubecolor get -o=wide --show-labels"
abbr --add ksysgowidesl "kubecolor --namespace=kube-system get -o=wide --show-labels"
abbr --add kgpoowidesl "kubecolor get pods -o=wide --show-labels"
abbr --add ksysgpoowidesl "kubecolor --namespace=kube-system get pods -o=wide --show-labels"
abbr --add kgdepowidesl "kubecolor get deployment -o=wide --show-labels"
abbr --add ksysgdepowidesl "kubecolor --namespace=kube-system get deployment -o=wide --show-labels"
abbr --add kgstsowidesl "kubecolor get statefulset -o=wide --show-labels"
abbr --add ksysgstsowidesl "kubecolor --namespace=kube-system get statefulset -o=wide --show-labels"
abbr --add kgsvcowidesl "kubecolor get service -o=wide --show-labels"
abbr --add ksysgsvcowidesl "kubecolor --namespace=kube-system get service -o=wide --show-labels"
abbr --add kgingowidesl "kubecolor get ingress -o=wide --show-labels"
abbr --add ksysgingowidesl "kubecolor --namespace=kube-system get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "kubecolor get configmap -o=wide --show-labels"
abbr --add ksysgcmowidesl "kubecolor --namespace=kube-system get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "kubecolor get secret -o=wide --show-labels"
abbr --add ksysgsecowidesl "kubecolor --namespace=kube-system get secret -o=wide --show-labels"
abbr --add kgnoowidesl "kubecolor get nodes -o=wide --show-labels"
abbr --add kgnsowidesl "kubecolor get namespaces -o=wide --show-labels"
abbr --add kgslowide "kubecolor get --show-labels -o=wide"
abbr --add ksysgslowide "kubecolor --namespace=kube-system get --show-labels -o=wide"
abbr --add kgposlowide "kubecolor get pods --show-labels -o=wide"
abbr --add ksysgposlowide "kubecolor --namespace=kube-system get pods --show-labels -o=wide"
abbr --add kgdepslowide "kubecolor get deployment --show-labels -o=wide"
abbr --add ksysgdepslowide "kubecolor --namespace=kube-system get deployment --show-labels -o=wide"
abbr --add kgstsslowide "kubecolor get statefulset --show-labels -o=wide"
abbr --add ksysgstsslowide "kubecolor --namespace=kube-system get statefulset --show-labels -o=wide"
abbr --add kgsvcslowide "kubecolor get service --show-labels -o=wide"
abbr --add ksysgsvcslowide "kubecolor --namespace=kube-system get service --show-labels -o=wide"
abbr --add kgingslowide "kubecolor get ingress --show-labels -o=wide"
abbr --add ksysgingslowide "kubecolor --namespace=kube-system get ingress --show-labels -o=wide"
abbr --add kgcmslowide "kubecolor get configmap --show-labels -o=wide"
abbr --add ksysgcmslowide "kubecolor --namespace=kube-system get configmap --show-labels -o=wide"
abbr --add kgsecslowide "kubecolor get secret --show-labels -o=wide"
abbr --add ksysgsecslowide "kubecolor --namespace=kube-system get secret --show-labels -o=wide"
abbr --add kgnoslowide "kubecolor get nodes --show-labels -o=wide"
abbr --add kgnsslowide "kubecolor get namespaces --show-labels -o=wide"
abbr --add kgojsonall "kubecolor get -o=json --all-namespaces"
abbr --add kgpoojsonall "kubecolor get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "kubecolor get deployment -o=json --all-namespaces"
abbr --add kgstsojsonall "kubecolor get statefulset -o=json --all-namespaces"
abbr --add kgsvcojsonall "kubecolor get service -o=json --all-namespaces"
abbr --add kgingojsonall "kubecolor get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "kubecolor get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "kubecolor get secret -o=json --all-namespaces"
abbr --add kgallojson "kubecolor get --all-namespaces -o=json"
abbr --add kgpoallojson "kubecolor get pods --all-namespaces -o=json"
abbr --add kgdepallojson "kubecolor get deployment --all-namespaces -o=json"
abbr --add kgstsallojson "kubecolor get statefulset --all-namespaces -o=json"
abbr --add kgsvcallojson "kubecolor get service --all-namespaces -o=json"
abbr --add kgingallojson "kubecolor get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "kubecolor get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "kubecolor get secret --all-namespaces -o=json"
abbr --add kgallsl "kubecolor get --all-namespaces --show-labels"
abbr --add kgpoallsl "kubecolor get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "kubecolor get deployment --all-namespaces --show-labels"
abbr --add kgstsallsl "kubecolor get statefulset --all-namespaces --show-labels"
abbr --add kgsvcallsl "kubecolor get service --all-namespaces --show-labels"
abbr --add kgingallsl "kubecolor get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "kubecolor get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "kubecolor get secret --all-namespaces --show-labels"
abbr --add kgslall "kubecolor get --show-labels --all-namespaces"
abbr --add kgposlall "kubecolor get pods --show-labels --all-namespaces"
abbr --add kgdepslall "kubecolor get deployment --show-labels --all-namespaces"
abbr --add kgstsslall "kubecolor get statefulset --show-labels --all-namespaces"
abbr --add kgsvcslall "kubecolor get service --show-labels --all-namespaces"
abbr --add kgingslall "kubecolor get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "kubecolor get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "kubecolor get secret --show-labels --all-namespaces"
abbr --add kgallw "kubecolor get --all-namespaces --watch"
abbr --add kgpoallw "kubecolor get pods --all-namespaces --watch"
abbr --add kgdepallw "kubecolor get deployment --all-namespaces --watch"
abbr --add kgstsallw "kubecolor get statefulset --all-namespaces --watch"
abbr --add kgsvcallw "kubecolor get service --all-namespaces --watch"
abbr --add kgingallw "kubecolor get ingress --all-namespaces --watch"
abbr --add kgcmallw "kubecolor get configmap --all-namespaces --watch"
abbr --add kgsecallw "kubecolor get secret --all-namespaces --watch"
abbr --add kgwall "kubecolor get --watch --all-namespaces"
abbr --add kgpowall "kubecolor get pods --watch --all-namespaces"
abbr --add kgdepwall "kubecolor get deployment --watch --all-namespaces"
abbr --add kgstswall "kubecolor get statefulset --watch --all-namespaces"
abbr --add kgsvcwall "kubecolor get service --watch --all-namespaces"
abbr --add kgingwall "kubecolor get ingress --watch --all-namespaces"
abbr --add kgcmwall "kubecolor get configmap --watch --all-namespaces"
abbr --add kgsecwall "kubecolor get secret --watch --all-namespaces"
abbr --add kgslw "kubecolor get --show-labels --watch"
abbr --add ksysgslw "kubecolor --namespace=kube-system get --show-labels --watch"
abbr --add kgposlw "kubecolor get pods --show-labels --watch"
abbr --add ksysgposlw "kubecolor --namespace=kube-system get pods --show-labels --watch"
abbr --add kgdepslw "kubecolor get deployment --show-labels --watch"
abbr --add ksysgdepslw "kubecolor --namespace=kube-system get deployment --show-labels --watch"
abbr --add kgstsslw "kubecolor get statefulset --show-labels --watch"
abbr --add ksysgstsslw "kubecolor --namespace=kube-system get statefulset --show-labels --watch"
abbr --add kgsvcslw "kubecolor get service --show-labels --watch"
abbr --add ksysgsvcslw "kubecolor --namespace=kube-system get service --show-labels --watch"
abbr --add kgingslw "kubecolor get ingress --show-labels --watch"
abbr --add ksysgingslw "kubecolor --namespace=kube-system get ingress --show-labels --watch"
abbr --add kgcmslw "kubecolor get configmap --show-labels --watch"
abbr --add ksysgcmslw "kubecolor --namespace=kube-system get configmap --show-labels --watch"
abbr --add kgsecslw "kubecolor get secret --show-labels --watch"
abbr --add ksysgsecslw "kubecolor --namespace=kube-system get secret --show-labels --watch"
abbr --add kgnoslw "kubecolor get nodes --show-labels --watch"
abbr --add kgnsslw "kubecolor get namespaces --show-labels --watch"
abbr --add kgwsl "kubecolor get --watch --show-labels"
abbr --add ksysgwsl "kubecolor --namespace=kube-system get --watch --show-labels"
abbr --add kgpowsl "kubecolor get pods --watch --show-labels"
abbr --add ksysgpowsl "kubecolor --namespace=kube-system get pods --watch --show-labels"
abbr --add kgdepwsl "kubecolor get deployment --watch --show-labels"
abbr --add ksysgdepwsl "kubecolor --namespace=kube-system get deployment --watch --show-labels"
abbr --add kgstswsl "kubecolor get statefulset --watch --show-labels"
abbr --add ksysgstswsl "kubecolor --namespace=kube-system get statefulset --watch --show-labels"
abbr --add kgsvcwsl "kubecolor get service --watch --show-labels"
abbr --add ksysgsvcwsl "kubecolor --namespace=kube-system get service --watch --show-labels"
abbr --add kgingwsl "kubecolor get ingress --watch --show-labels"
abbr --add ksysgingwsl "kubecolor --namespace=kube-system get ingress --watch --show-labels"
abbr --add kgcmwsl "kubecolor get configmap --watch --show-labels"
abbr --add ksysgcmwsl "kubecolor --namespace=kube-system get configmap --watch --show-labels"
abbr --add kgsecwsl "kubecolor get secret --watch --show-labels"
abbr --add ksysgsecwsl "kubecolor --namespace=kube-system get secret --watch --show-labels"
abbr --add kgnowsl "kubecolor get nodes --watch --show-labels"
abbr --add kgnswsl "kubecolor get namespaces --watch --show-labels"
abbr --add kgowideallsl "kubecolor get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "kubecolor get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "kubecolor get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgstsowideallsl "kubecolor get statefulset -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "kubecolor get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "kubecolor get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "kubecolor get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "kubecolor get secret -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "kubecolor get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "kubecolor get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "kubecolor get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgstsowideslall "kubecolor get statefulset -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "kubecolor get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "kubecolor get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "kubecolor get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "kubecolor get secret -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "kubecolor get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "kubecolor get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "kubecolor get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgstsallowidesl "kubecolor get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "kubecolor get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "kubecolor get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "kubecolor get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "kubecolor get secret --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "kubecolor get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "kubecolor get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "kubecolor get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgstsallslowide "kubecolor get statefulset --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "kubecolor get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "kubecolor get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "kubecolor get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "kubecolor get secret --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "kubecolor get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "kubecolor get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "kubecolor get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgstsslowideall "kubecolor get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "kubecolor get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "kubecolor get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "kubecolor get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "kubecolor get secret --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "kubecolor get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "kubecolor get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "kubecolor get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgstsslallowide "kubecolor get statefulset --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "kubecolor get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "kubecolor get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "kubecolor get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "kubecolor get secret --show-labels --all-namespaces -o=wide"
abbr --add kgallslw "kubecolor get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "kubecolor get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "kubecolor get deployment --all-namespaces --show-labels --watch"
abbr --add kgstsallslw "kubecolor get statefulset --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "kubecolor get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "kubecolor get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "kubecolor get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "kubecolor get secret --all-namespaces --show-labels --watch"
abbr --add kgallwsl "kubecolor get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "kubecolor get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "kubecolor get deployment --all-namespaces --watch --show-labels"
abbr --add kgstsallwsl "kubecolor get statefulset --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "kubecolor get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "kubecolor get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "kubecolor get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "kubecolor get secret --all-namespaces --watch --show-labels"
abbr --add kgslallw "kubecolor get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "kubecolor get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "kubecolor get deployment --show-labels --all-namespaces --watch"
abbr --add kgstsslallw "kubecolor get statefulset --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "kubecolor get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "kubecolor get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "kubecolor get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "kubecolor get secret --show-labels --all-namespaces --watch"
abbr --add kgslwall "kubecolor get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "kubecolor get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "kubecolor get deployment --show-labels --watch --all-namespaces"
abbr --add kgstsslwall "kubecolor get statefulset --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "kubecolor get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "kubecolor get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "kubecolor get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "kubecolor get secret --show-labels --watch --all-namespaces"
abbr --add kgwallsl "kubecolor get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "kubecolor get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "kubecolor get deployment --watch --all-namespaces --show-labels"
abbr --add kgstswallsl "kubecolor get statefulset --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "kubecolor get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "kubecolor get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "kubecolor get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "kubecolor get secret --watch --all-namespaces --show-labels"
abbr --add kgwslall "kubecolor get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "kubecolor get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "kubecolor get deployment --watch --show-labels --all-namespaces"
abbr --add kgstswslall "kubecolor get statefulset --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "kubecolor get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "kubecolor get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "kubecolor get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "kubecolor get secret --watch --show-labels --all-namespaces"
abbr --add kgf "kubecolor get --recursive -f"
abbr --add kdf "kubecolor describe --recursive -f"
abbr --add krmf "kubecolor delete --recursive -f"
abbr --add kgoyamlf "kubecolor get -o=yaml --recursive -f"
abbr --add kgowidef "kubecolor get -o=wide --recursive -f"
abbr --add kgojsonf "kubecolor get -o=json --recursive -f"
abbr --add kgslf "kubecolor get --show-labels --recursive -f"
abbr --add kgwf "kubecolor get --watch --recursive -f"
abbr --add kgowideslf "kubecolor get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubecolor get --show-labels -o=wide --recursive -f"
abbr --add kgslwf "kubecolor get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubecolor get --watch --show-labels --recursive -f"
abbr --add kgl "kubecolor get -l"
abbr --add ksysgl "kubecolor --namespace=kube-system get -l"
abbr --add kdl "kubecolor describe -l"
abbr --add ksysdl "kubecolor --namespace=kube-system describe -l"
abbr --add krml "kubecolor delete -l"
abbr --add ksysrml "kubecolor --namespace=kube-system delete -l"
abbr --add kgpol "kubecolor get pods -l"
abbr --add ksysgpol "kubecolor --namespace=kube-system get pods -l"
abbr --add kdpol "kubecolor describe pods -l"
abbr --add ksysdpol "kubecolor --namespace=kube-system describe pods -l"
abbr --add krmpol "kubecolor delete pods -l"
abbr --add ksysrmpol "kubecolor --namespace=kube-system delete pods -l"
abbr --add kgdepl "kubecolor get deployment -l"
abbr --add ksysgdepl "kubecolor --namespace=kube-system get deployment -l"
abbr --add kddepl "kubecolor describe deployment -l"
abbr --add ksysddepl "kubecolor --namespace=kube-system describe deployment -l"
abbr --add krmdepl "kubecolor delete deployment -l"
abbr --add ksysrmdepl "kubecolor --namespace=kube-system delete deployment -l"
abbr --add kgstsl "kubecolor get statefulset -l"
abbr --add ksysgstsl "kubecolor --namespace=kube-system get statefulset -l"
abbr --add kdstsl "kubecolor describe statefulset -l"
abbr --add ksysdstsl "kubecolor --namespace=kube-system describe statefulset -l"
abbr --add krmstsl "kubecolor delete statefulset -l"
abbr --add ksysrmstsl "kubecolor --namespace=kube-system delete statefulset -l"
abbr --add kgsvcl "kubecolor get service -l"
abbr --add ksysgsvcl "kubecolor --namespace=kube-system get service -l"
abbr --add kdsvcl "kubecolor describe service -l"
abbr --add ksysdsvcl "kubecolor --namespace=kube-system describe service -l"
abbr --add krmsvcl "kubecolor delete service -l"
abbr --add ksysrmsvcl "kubecolor --namespace=kube-system delete service -l"
abbr --add kgingl "kubecolor get ingress -l"
abbr --add ksysgingl "kubecolor --namespace=kube-system get ingress -l"
abbr --add kdingl "kubecolor describe ingress -l"
abbr --add ksysdingl "kubecolor --namespace=kube-system describe ingress -l"
abbr --add krmingl "kubecolor delete ingress -l"
abbr --add ksysrmingl "kubecolor --namespace=kube-system delete ingress -l"
abbr --add kgcml "kubecolor get configmap -l"
abbr --add ksysgcml "kubecolor --namespace=kube-system get configmap -l"
abbr --add kdcml "kubecolor describe configmap -l"
abbr --add ksysdcml "kubecolor --namespace=kube-system describe configmap -l"
abbr --add krmcml "kubecolor delete configmap -l"
abbr --add ksysrmcml "kubecolor --namespace=kube-system delete configmap -l"
abbr --add kgsecl "kubecolor get secret -l"
abbr --add ksysgsecl "kubecolor --namespace=kube-system get secret -l"
abbr --add kdsecl "kubecolor describe secret -l"
abbr --add ksysdsecl "kubecolor --namespace=kube-system describe secret -l"
abbr --add krmsecl "kubecolor delete secret -l"
abbr --add ksysrmsecl "kubecolor --namespace=kube-system delete secret -l"
abbr --add kgnol "kubecolor get nodes -l"
abbr --add kdnol "kubecolor describe nodes -l"
abbr --add kgnsl "kubecolor get namespaces -l"
abbr --add kdnsl "kubecolor describe namespaces -l"
abbr --add krmnsl "kubecolor delete namespaces -l"
abbr --add kgoyamll "kubecolor get -o=yaml -l"
abbr --add ksysgoyamll "kubecolor --namespace=kube-system get -o=yaml -l"
abbr --add kgpooyamll "kubecolor get pods -o=yaml -l"
abbr --add ksysgpooyamll "kubecolor --namespace=kube-system get pods -o=yaml -l"
abbr --add kgdepoyamll "kubecolor get deployment -o=yaml -l"
abbr --add ksysgdepoyamll "kubecolor --namespace=kube-system get deployment -o=yaml -l"
abbr --add kgstsoyamll "kubecolor get statefulset -o=yaml -l"
abbr --add ksysgstsoyamll "kubecolor --namespace=kube-system get statefulset -o=yaml -l"
abbr --add kgsvcoyamll "kubecolor get service -o=yaml -l"
abbr --add ksysgsvcoyamll "kubecolor --namespace=kube-system get service -o=yaml -l"
abbr --add kgingoyamll "kubecolor get ingress -o=yaml -l"
abbr --add ksysgingoyamll "kubecolor --namespace=kube-system get ingress -o=yaml -l"
abbr --add kgcmoyamll "kubecolor get configmap -o=yaml -l"
abbr --add ksysgcmoyamll "kubecolor --namespace=kube-system get configmap -o=yaml -l"
abbr --add kgsecoyamll "kubecolor get secret -o=yaml -l"
abbr --add ksysgsecoyamll "kubecolor --namespace=kube-system get secret -o=yaml -l"
abbr --add kgnooyamll "kubecolor get nodes -o=yaml -l"
abbr --add kgnsoyamll "kubecolor get namespaces -o=yaml -l"
abbr --add kgowidel "kubecolor get -o=wide -l"
abbr --add ksysgowidel "kubecolor --namespace=kube-system get -o=wide -l"
abbr --add kgpoowidel "kubecolor get pods -o=wide -l"
abbr --add ksysgpoowidel "kubecolor --namespace=kube-system get pods -o=wide -l"
abbr --add kgdepowidel "kubecolor get deployment -o=wide -l"
abbr --add ksysgdepowidel "kubecolor --namespace=kube-system get deployment -o=wide -l"
abbr --add kgstsowidel "kubecolor get statefulset -o=wide -l"
abbr --add ksysgstsowidel "kubecolor --namespace=kube-system get statefulset -o=wide -l"
abbr --add kgsvcowidel "kubecolor get service -o=wide -l"
abbr --add ksysgsvcowidel "kubecolor --namespace=kube-system get service -o=wide -l"
abbr --add kgingowidel "kubecolor get ingress -o=wide -l"
abbr --add ksysgingowidel "kubecolor --namespace=kube-system get ingress -o=wide -l"
abbr --add kgcmowidel "kubecolor get configmap -o=wide -l"
abbr --add ksysgcmowidel "kubecolor --namespace=kube-system get configmap -o=wide -l"
abbr --add kgsecowidel "kubecolor get secret -o=wide -l"
abbr --add ksysgsecowidel "kubecolor --namespace=kube-system get secret -o=wide -l"
abbr --add kgnoowidel "kubecolor get nodes -o=wide -l"
abbr --add kgnsowidel "kubecolor get namespaces -o=wide -l"
abbr --add kgojsonl "kubecolor get -o=json -l"
abbr --add ksysgojsonl "kubecolor --namespace=kube-system get -o=json -l"
abbr --add kgpoojsonl "kubecolor get pods -o=json -l"
abbr --add ksysgpoojsonl "kubecolor --namespace=kube-system get pods -o=json -l"
abbr --add kgdepojsonl "kubecolor get deployment -o=json -l"
abbr --add ksysgdepojsonl "kubecolor --namespace=kube-system get deployment -o=json -l"
abbr --add kgstsojsonl "kubecolor get statefulset -o=json -l"
abbr --add ksysgstsojsonl "kubecolor --namespace=kube-system get statefulset -o=json -l"
abbr --add kgsvcojsonl "kubecolor get service -o=json -l"
abbr --add ksysgsvcojsonl "kubecolor --namespace=kube-system get service -o=json -l"
abbr --add kgingojsonl "kubecolor get ingress -o=json -l"
abbr --add ksysgingojsonl "kubecolor --namespace=kube-system get ingress -o=json -l"
abbr --add kgcmojsonl "kubecolor get configmap -o=json -l"
abbr --add ksysgcmojsonl "kubecolor --namespace=kube-system get configmap -o=json -l"
abbr --add kgsecojsonl "kubecolor get secret -o=json -l"
abbr --add ksysgsecojsonl "kubecolor --namespace=kube-system get secret -o=json -l"
abbr --add kgnoojsonl "kubecolor get nodes -o=json -l"
abbr --add kgnsojsonl "kubecolor get namespaces -o=json -l"
abbr --add kgsll "kubecolor get --show-labels -l"
abbr --add ksysgsll "kubecolor --namespace=kube-system get --show-labels -l"
abbr --add kgposll "kubecolor get pods --show-labels -l"
abbr --add ksysgposll "kubecolor --namespace=kube-system get pods --show-labels -l"
abbr --add kgdepsll "kubecolor get deployment --show-labels -l"
abbr --add ksysgdepsll "kubecolor --namespace=kube-system get deployment --show-labels -l"
abbr --add kgstssll "kubecolor get statefulset --show-labels -l"
abbr --add ksysgstssll "kubecolor --namespace=kube-system get statefulset --show-labels -l"
abbr --add kgsvcsll "kubecolor get service --show-labels -l"
abbr --add ksysgsvcsll "kubecolor --namespace=kube-system get service --show-labels -l"
abbr --add kgingsll "kubecolor get ingress --show-labels -l"
abbr --add ksysgingsll "kubecolor --namespace=kube-system get ingress --show-labels -l"
abbr --add kgcmsll "kubecolor get configmap --show-labels -l"
abbr --add ksysgcmsll "kubecolor --namespace=kube-system get configmap --show-labels -l"
abbr --add kgsecsll "kubecolor get secret --show-labels -l"
abbr --add ksysgsecsll "kubecolor --namespace=kube-system get secret --show-labels -l"
abbr --add kgnosll "kubecolor get nodes --show-labels -l"
abbr --add kgnssll "kubecolor get namespaces --show-labels -l"
abbr --add kgwl "kubecolor get --watch -l"
abbr --add ksysgwl "kubecolor --namespace=kube-system get --watch -l"
abbr --add kgpowl "kubecolor get pods --watch -l"
abbr --add ksysgpowl "kubecolor --namespace=kube-system get pods --watch -l"
abbr --add kgdepwl "kubecolor get deployment --watch -l"
abbr --add ksysgdepwl "kubecolor --namespace=kube-system get deployment --watch -l"
abbr --add kgstswl "kubecolor get statefulset --watch -l"
abbr --add ksysgstswl "kubecolor --namespace=kube-system get statefulset --watch -l"
abbr --add kgsvcwl "kubecolor get service --watch -l"
abbr --add ksysgsvcwl "kubecolor --namespace=kube-system get service --watch -l"
abbr --add kgingwl "kubecolor get ingress --watch -l"
abbr --add ksysgingwl "kubecolor --namespace=kube-system get ingress --watch -l"
abbr --add kgcmwl "kubecolor get configmap --watch -l"
abbr --add ksysgcmwl "kubecolor --namespace=kube-system get configmap --watch -l"
abbr --add kgsecwl "kubecolor get secret --watch -l"
abbr --add ksysgsecwl "kubecolor --namespace=kube-system get secret --watch -l"
abbr --add kgnowl "kubecolor get nodes --watch -l"
abbr --add kgnswl "kubecolor get namespaces --watch -l"
abbr --add kgowidesll "kubecolor get -o=wide --show-labels -l"
abbr --add ksysgowidesll "kubecolor --namespace=kube-system get -o=wide --show-labels -l"
abbr --add kgpoowidesll "kubecolor get pods -o=wide --show-labels -l"
abbr --add ksysgpoowidesll "kubecolor --namespace=kube-system get pods -o=wide --show-labels -l"
abbr --add kgdepowidesll "kubecolor get deployment -o=wide --show-labels -l"
abbr --add ksysgdepowidesll "kubecolor --namespace=kube-system get deployment -o=wide --show-labels -l"
abbr --add kgstsowidesll "kubecolor get statefulset -o=wide --show-labels -l"
abbr --add ksysgstsowidesll "kubecolor --namespace=kube-system get statefulset -o=wide --show-labels -l"
abbr --add kgsvcowidesll "kubecolor get service -o=wide --show-labels -l"
abbr --add ksysgsvcowidesll "kubecolor --namespace=kube-system get service -o=wide --show-labels -l"
abbr --add kgingowidesll "kubecolor get ingress -o=wide --show-labels -l"
abbr --add ksysgingowidesll "kubecolor --namespace=kube-system get ingress -o=wide --show-labels -l"
abbr --add kgcmowidesll "kubecolor get configmap -o=wide --show-labels -l"
abbr --add ksysgcmowidesll "kubecolor --namespace=kube-system get configmap -o=wide --show-labels -l"
abbr --add kgsecowidesll "kubecolor get secret -o=wide --show-labels -l"
abbr --add ksysgsecowidesll "kubecolor --namespace=kube-system get secret -o=wide --show-labels -l"
abbr --add kgnoowidesll "kubecolor get nodes -o=wide --show-labels -l"
abbr --add kgnsowidesll "kubecolor get namespaces -o=wide --show-labels -l"
abbr --add kgslowidel "kubecolor get --show-labels -o=wide -l"
abbr --add ksysgslowidel "kubecolor --namespace=kube-system get --show-labels -o=wide -l"
abbr --add kgposlowidel "kubecolor get pods --show-labels -o=wide -l"
abbr --add ksysgposlowidel "kubecolor --namespace=kube-system get pods --show-labels -o=wide -l"
abbr --add kgdepslowidel "kubecolor get deployment --show-labels -o=wide -l"
abbr --add ksysgdepslowidel "kubecolor --namespace=kube-system get deployment --show-labels -o=wide -l"
abbr --add kgstsslowidel "kubecolor get statefulset --show-labels -o=wide -l"
abbr --add ksysgstsslowidel "kubecolor --namespace=kube-system get statefulset --show-labels -o=wide -l"
abbr --add kgsvcslowidel "kubecolor get service --show-labels -o=wide -l"
abbr --add ksysgsvcslowidel "kubecolor --namespace=kube-system get service --show-labels -o=wide -l"
abbr --add kgingslowidel "kubecolor get ingress --show-labels -o=wide -l"
abbr --add ksysgingslowidel "kubecolor --namespace=kube-system get ingress --show-labels -o=wide -l"
abbr --add kgcmslowidel "kubecolor get configmap --show-labels -o=wide -l"
abbr --add ksysgcmslowidel "kubecolor --namespace=kube-system get configmap --show-labels -o=wide -l"
abbr --add kgsecslowidel "kubecolor get secret --show-labels -o=wide -l"
abbr --add ksysgsecslowidel "kubecolor --namespace=kube-system get secret --show-labels -o=wide -l"
abbr --add kgnoslowidel "kubecolor get nodes --show-labels -o=wide -l"
abbr --add kgnsslowidel "kubecolor get namespaces --show-labels -o=wide -l"
abbr --add kgslwl "kubecolor get --show-labels --watch -l"
abbr --add ksysgslwl "kubecolor --namespace=kube-system get --show-labels --watch -l"
abbr --add kgposlwl "kubecolor get pods --show-labels --watch -l"
abbr --add ksysgposlwl "kubecolor --namespace=kube-system get pods --show-labels --watch -l"
abbr --add kgdepslwl "kubecolor get deployment --show-labels --watch -l"
abbr --add ksysgdepslwl "kubecolor --namespace=kube-system get deployment --show-labels --watch -l"
abbr --add kgstsslwl "kubecolor get statefulset --show-labels --watch -l"
abbr --add ksysgstsslwl "kubecolor --namespace=kube-system get statefulset --show-labels --watch -l"
abbr --add kgsvcslwl "kubecolor get service --show-labels --watch -l"
abbr --add ksysgsvcslwl "kubecolor --namespace=kube-system get service --show-labels --watch -l"
abbr --add kgingslwl "kubecolor get ingress --show-labels --watch -l"
abbr --add ksysgingslwl "kubecolor --namespace=kube-system get ingress --show-labels --watch -l"
abbr --add kgcmslwl "kubecolor get configmap --show-labels --watch -l"
abbr --add ksysgcmslwl "kubecolor --namespace=kube-system get configmap --show-labels --watch -l"
abbr --add kgsecslwl "kubecolor get secret --show-labels --watch -l"
abbr --add ksysgsecslwl "kubecolor --namespace=kube-system get secret --show-labels --watch -l"
abbr --add kgnoslwl "kubecolor get nodes --show-labels --watch -l"
abbr --add kgnsslwl "kubecolor get namespaces --show-labels --watch -l"
abbr --add kgwsll "kubecolor get --watch --show-labels -l"
abbr --add ksysgwsll "kubecolor --namespace=kube-system get --watch --show-labels -l"
abbr --add kgpowsll "kubecolor get pods --watch --show-labels -l"
abbr --add ksysgpowsll "kubecolor --namespace=kube-system get pods --watch --show-labels -l"
abbr --add kgdepwsll "kubecolor get deployment --watch --show-labels -l"
abbr --add ksysgdepwsll "kubecolor --namespace=kube-system get deployment --watch --show-labels -l"
abbr --add kgstswsll "kubecolor get statefulset --watch --show-labels -l"
abbr --add ksysgstswsll "kubecolor --namespace=kube-system get statefulset --watch --show-labels -l"
abbr --add kgsvcwsll "kubecolor get service --watch --show-labels -l"
abbr --add ksysgsvcwsll "kubecolor --namespace=kube-system get service --watch --show-labels -l"
abbr --add kgingwsll "kubecolor get ingress --watch --show-labels -l"
abbr --add ksysgingwsll "kubecolor --namespace=kube-system get ingress --watch --show-labels -l"
abbr --add kgcmwsll "kubecolor get configmap --watch --show-labels -l"
abbr --add ksysgcmwsll "kubecolor --namespace=kube-system get configmap --watch --show-labels -l"
abbr --add kgsecwsll "kubecolor get secret --watch --show-labels -l"
abbr --add ksysgsecwsll "kubecolor --namespace=kube-system get secret --watch --show-labels -l"
abbr --add kgnowsll "kubecolor get nodes --watch --show-labels -l"
abbr --add kgnswsll "kubecolor get namespaces --watch --show-labels -l"
abbr --add kexn "kubecolor exec -i -t --namespace"
abbr --add klon "kubecolor logs -f --namespace"
abbr --add kpfn "kubecolor port-forward --namespace"
abbr --add kgn "kubecolor get --namespace"
abbr --add kdn "kubecolor describe --namespace"
abbr --add krmn "kubecolor delete --namespace"
abbr --add kgpon "kubecolor get pods --namespace"
abbr --add kdpon "kubecolor describe pods --namespace"
abbr --add krmpon "kubecolor delete pods --namespace"
abbr --add kgdepn "kubecolor get deployment --namespace"
abbr --add kddepn "kubecolor describe deployment --namespace"
abbr --add krmdepn "kubecolor delete deployment --namespace"
abbr --add kgstsn "kubecolor get statefulset --namespace"
abbr --add kdstsn "kubecolor describe statefulset --namespace"
abbr --add krmstsn "kubecolor delete statefulset --namespace"
abbr --add kgsvcn "kubecolor get service --namespace"
abbr --add kdsvcn "kubecolor describe service --namespace"
abbr --add krmsvcn "kubecolor delete service --namespace"
abbr --add kgingn "kubecolor get ingress --namespace"
abbr --add kdingn "kubecolor describe ingress --namespace"
abbr --add krmingn "kubecolor delete ingress --namespace"
abbr --add kgcmn "kubecolor get configmap --namespace"
abbr --add kdcmn "kubecolor describe configmap --namespace"
abbr --add krmcmn "kubecolor delete configmap --namespace"
abbr --add kgsecn "kubecolor get secret --namespace"
abbr --add kdsecn "kubecolor describe secret --namespace"
abbr --add krmsecn "kubecolor delete secret --namespace"
abbr --add kgoyamln "kubecolor get -o=yaml --namespace"
abbr --add kgpooyamln "kubecolor get pods -o=yaml --namespace"
abbr --add kgdepoyamln "kubecolor get deployment -o=yaml --namespace"
abbr --add kgstsoyamln "kubecolor get statefulset -o=yaml --namespace"
abbr --add kgsvcoyamln "kubecolor get service -o=yaml --namespace"
abbr --add kgingoyamln "kubecolor get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "kubecolor get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "kubecolor get secret -o=yaml --namespace"
abbr --add kgowiden "kubecolor get -o=wide --namespace"
abbr --add kgpoowiden "kubecolor get pods -o=wide --namespace"
abbr --add kgdepowiden "kubecolor get deployment -o=wide --namespace"
abbr --add kgstsowiden "kubecolor get statefulset -o=wide --namespace"
abbr --add kgsvcowiden "kubecolor get service -o=wide --namespace"
abbr --add kgingowiden "kubecolor get ingress -o=wide --namespace"
abbr --add kgcmowiden "kubecolor get configmap -o=wide --namespace"
abbr --add kgsecowiden "kubecolor get secret -o=wide --namespace"
abbr --add kgojsonn "kubecolor get -o=json --namespace"
abbr --add kgpoojsonn "kubecolor get pods -o=json --namespace"
abbr --add kgdepojsonn "kubecolor get deployment -o=json --namespace"
abbr --add kgstsojsonn "kubecolor get statefulset -o=json --namespace"
abbr --add kgsvcojsonn "kubecolor get service -o=json --namespace"
abbr --add kgingojsonn "kubecolor get ingress -o=json --namespace"
abbr --add kgcmojsonn "kubecolor get configmap -o=json --namespace"
abbr --add kgsecojsonn "kubecolor get secret -o=json --namespace"
abbr --add kgsln "kubecolor get --show-labels --namespace"
abbr --add kgposln "kubecolor get pods --show-labels --namespace"
abbr --add kgdepsln "kubecolor get deployment --show-labels --namespace"
abbr --add kgstssln "kubecolor get statefulset --show-labels --namespace"
abbr --add kgsvcsln "kubecolor get service --show-labels --namespace"
abbr --add kgingsln "kubecolor get ingress --show-labels --namespace"
abbr --add kgcmsln "kubecolor get configmap --show-labels --namespace"
abbr --add kgsecsln "kubecolor get secret --show-labels --namespace"
abbr --add kgwn "kubecolor get --watch --namespace"
abbr --add kgpown "kubecolor get pods --watch --namespace"
abbr --add kgdepwn "kubecolor get deployment --watch --namespace"
abbr --add kgstswn "kubecolor get statefulset --watch --namespace"
abbr --add kgsvcwn "kubecolor get service --watch --namespace"
abbr --add kgingwn "kubecolor get ingress --watch --namespace"
abbr --add kgcmwn "kubecolor get configmap --watch --namespace"
abbr --add kgsecwn "kubecolor get secret --watch --namespace"
abbr --add kgowidesln "kubecolor get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "kubecolor get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "kubecolor get deployment -o=wide --show-labels --namespace"
abbr --add kgstsowidesln "kubecolor get statefulset -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "kubecolor get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "kubecolor get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "kubecolor get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "kubecolor get secret -o=wide --show-labels --namespace"
abbr --add kgslowiden "kubecolor get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "kubecolor get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "kubecolor get deployment --show-labels -o=wide --namespace"
abbr --add kgstsslowiden "kubecolor get statefulset --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "kubecolor get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "kubecolor get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "kubecolor get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "kubecolor get secret --show-labels -o=wide --namespace"
abbr --add kgslwn "kubecolor get --show-labels --watch --namespace"
abbr --add kgposlwn "kubecolor get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "kubecolor get deployment --show-labels --watch --namespace"
abbr --add kgstsslwn "kubecolor get statefulset --show-labels --watch --namespace"
abbr --add kgsvcslwn "kubecolor get service --show-labels --watch --namespace"
abbr --add kgingslwn "kubecolor get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "kubecolor get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "kubecolor get secret --show-labels --watch --namespace"
abbr --add kgwsln "kubecolor get --watch --show-labels --namespace"
abbr --add kgpowsln "kubecolor get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "kubecolor get deployment --watch --show-labels --namespace"
abbr --add kgstswsln "kubecolor get statefulset --watch --show-labels --namespace"
abbr --add kgsvcwsln "kubecolor get service --watch --show-labels --namespace"
abbr --add kgingwsln "kubecolor get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "kubecolor get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "kubecolor get secret --watch --show-labels --namespace"
