# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add k "kubecolor"
abbr --add ksys "kubecolor --namespace=kube-system"
abbr --add ka "kubecolor apply --recursive -f"
abbr --add ksysa "kubecolor --namespace=kube-system apply --recursive -f"
abbr --add kak "kubecolor apply -k"
abbr --add kk "kubecolor kustomize"
abbr --add kex "kubecolor exec -i -t"
abbr --add ksysex "kubecolor --namespace=kube-system exec -i -t"
abbr --add klo "kubecolor logs -f"
abbr --add ksyslo "kubecolor --namespace=kube-system logs -f"
abbr --add klop "kubecolor logs -f -p"
abbr --add ksyslop "kubecolor --namespace=kube-system logs -f -p"
abbr --add kp "kubecolor proxy"
abbr --add kpf "kubecolor port-forward"
abbr --add kg "kubecolor get"
abbr --add ksysg "kubecolor --namespace=kube-system get"
abbr --add kd "kubecolor describe"
abbr --add ksysd "kubecolor --namespace=kube-system describe"
abbr --add krm "kubecolor delete"
abbr --add ksysrm "kubecolor --namespace=kube-system delete"
abbr --add krun "kubecolor run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubecolor --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kgpo "kubecolor get pods"
abbr --add ksysgpo "kubecolor --namespace=kube-system get pods"
abbr --add kdpo "kubecolor describe pods"
abbr --add ksysdpo "kubecolor --namespace=kube-system describe pods"
abbr --add krmpo "kubecolor delete pods"
abbr --add ksysrmpo "kubecolor --namespace=kube-system delete pods"
abbr --add kgdep "kubecolor get deployment"
abbr --add ksysgdep "kubecolor --namespace=kube-system get deployment"
abbr --add kddep "kubecolor describe deployment"
abbr --add ksysddep "kubecolor --namespace=kube-system describe deployment"
abbr --add krmdep "kubecolor delete deployment"
abbr --add ksysrmdep "kubecolor --namespace=kube-system delete deployment"
abbr --add kgsts "kubecolor get statefulset"
abbr --add ksysgsts "kubecolor --namespace=kube-system get statefulset"
abbr --add kdsts "kubecolor describe statefulset"
abbr --add ksysdsts "kubecolor --namespace=kube-system describe statefulset"
abbr --add krmsts "kubecolor delete statefulset"
abbr --add ksysrmsts "kubecolor --namespace=kube-system delete statefulset"
abbr --add kgsvc "kubecolor get service"
abbr --add ksysgsvc "kubecolor --namespace=kube-system get service"
abbr --add kdsvc "kubecolor describe service"
abbr --add ksysdsvc "kubecolor --namespace=kube-system describe service"
abbr --add krmsvc "kubecolor delete service"
abbr --add ksysrmsvc "kubecolor --namespace=kube-system delete service"
abbr --add kging "kubecolor get ingress"
abbr --add ksysging "kubecolor --namespace=kube-system get ingress"
abbr --add kding "kubecolor describe ingress"
abbr --add ksysding "kubecolor --namespace=kube-system describe ingress"
abbr --add krming "kubecolor delete ingress"
abbr --add ksysrming "kubecolor --namespace=kube-system delete ingress"
abbr --add kgcm "kubecolor get configmap"
abbr --add ksysgcm "kubecolor --namespace=kube-system get configmap"
abbr --add kdcm "kubecolor describe configmap"
abbr --add ksysdcm "kubecolor --namespace=kube-system describe configmap"
abbr --add krmcm "kubecolor delete configmap"
abbr --add ksysrmcm "kubecolor --namespace=kube-system delete configmap"
abbr --add kgsec "kubecolor get secret"
abbr --add ksysgsec "kubecolor --namespace=kube-system get secret"
abbr --add kdsec "kubecolor describe secret"
abbr --add ksysdsec "kubecolor --namespace=kube-system describe secret"
abbr --add krmsec "kubecolor delete secret"
abbr --add ksysrmsec "kubecolor --namespace=kube-system delete secret"
abbr --add kgno "kubecolor get nodes"
abbr --add kdno "kubecolor describe nodes"
abbr --add kgns "kubecolor get namespaces"
abbr --add kdns "kubecolor describe namespaces"
abbr --add krmns "kubecolor delete namespaces"
abbr --add kgoyaml "kubecolor get -o=yaml"
abbr --add ksysgoyaml "kubecolor --namespace=kube-system get -o=yaml"
abbr --add kgpooyaml "kubecolor get pods -o=yaml"
abbr --add ksysgpooyaml "kubecolor --namespace=kube-system get pods -o=yaml"
abbr --add kgdepoyaml "kubecolor get deployment -o=yaml"
abbr --add ksysgdepoyaml "kubecolor --namespace=kube-system get deployment -o=yaml"
abbr --add kgstsoyaml "kubecolor get statefulset -o=yaml"
abbr --add ksysgstsoyaml "kubecolor --namespace=kube-system get statefulset -o=yaml"
abbr --add kgsvcoyaml "kubecolor get service -o=yaml"
abbr --add ksysgsvcoyaml "kubecolor --namespace=kube-system get service -o=yaml"
abbr --add kgingoyaml "kubecolor get ingress -o=yaml"
abbr --add ksysgingoyaml "kubecolor --namespace=kube-system get ingress -o=yaml"
abbr --add kgcmoyaml "kubecolor get configmap -o=yaml"
abbr --add ksysgcmoyaml "kubecolor --namespace=kube-system get configmap -o=yaml"
abbr --add kgsecoyaml "kubecolor get secret -o=yaml"
abbr --add ksysgsecoyaml "kubecolor --namespace=kube-system get secret -o=yaml"
abbr --add kgnooyaml "kubecolor get nodes -o=yaml"
abbr --add kgnsoyaml "kubecolor get namespaces -o=yaml"
abbr --add kgowide "kubecolor get -o=wide"
abbr --add ksysgowide "kubecolor --namespace=kube-system get -o=wide"
abbr --add kgpoowide "kubecolor get pods -o=wide"
abbr --add ksysgpoowide "kubecolor --namespace=kube-system get pods -o=wide"
abbr --add kgdepowide "kubecolor get deployment -o=wide"
abbr --add ksysgdepowide "kubecolor --namespace=kube-system get deployment -o=wide"
abbr --add kgstsowide "kubecolor get statefulset -o=wide"
abbr --add ksysgstsowide "kubecolor --namespace=kube-system get statefulset -o=wide"
abbr --add kgsvcowide "kubecolor get service -o=wide"
abbr --add ksysgsvcowide "kubecolor --namespace=kube-system get service -o=wide"
abbr --add kgingowide "kubecolor get ingress -o=wide"
abbr --add ksysgingowide "kubecolor --namespace=kube-system get ingress -o=wide"
abbr --add kgcmowide "kubecolor get configmap -o=wide"
abbr --add ksysgcmowide "kubecolor --namespace=kube-system get configmap -o=wide"
abbr --add kgsecowide "kubecolor get secret -o=wide"
abbr --add ksysgsecowide "kubecolor --namespace=kube-system get secret -o=wide"
abbr --add kgnoowide "kubecolor get nodes -o=wide"
abbr --add kgnsowide "kubecolor get namespaces -o=wide"
abbr --add kgojson "kubecolor get -o=json"
abbr --add ksysgojson "kubecolor --namespace=kube-system get -o=json"
abbr --add kgpoojson "kubecolor get pods -o=json"
abbr --add ksysgpoojson "kubecolor --namespace=kube-system get pods -o=json"
abbr --add kgdepojson "kubecolor get deployment -o=json"
abbr --add ksysgdepojson "kubecolor --namespace=kube-system get deployment -o=json"
abbr --add kgstsojson "kubecolor get statefulset -o=json"
abbr --add ksysgstsojson "kubecolor --namespace=kube-system get statefulset -o=json"
abbr --add kgsvcojson "kubecolor get service -o=json"
abbr --add ksysgsvcojson "kubecolor --namespace=kube-system get service -o=json"
abbr --add kgingojson "kubecolor get ingress -o=json"
abbr --add ksysgingojson "kubecolor --namespace=kube-system get ingress -o=json"
abbr --add kgcmojson "kubecolor get configmap -o=json"
abbr --add ksysgcmojson "kubecolor --namespace=kube-system get configmap -o=json"
abbr --add kgsecojson "kubecolor get secret -o=json"
abbr --add ksysgsecojson "kubecolor --namespace=kube-system get secret -o=json"
abbr --add kgnoojson "kubecolor get nodes -o=json"
abbr --add kgnsojson "kubecolor get namespaces -o=json"
abbr --add kgall "kubecolor get --all-namespaces"
abbr --add kdall "kubecolor describe --all-namespaces"
abbr --add kgpoall "kubecolor get pods --all-namespaces"
abbr --add kdpoall "kubecolor describe pods --all-namespaces"
abbr --add kgdepall "kubecolor get deployment --all-namespaces"
abbr --add kddepall "kubecolor describe deployment --all-namespaces"
abbr --add kgstsall "kubecolor get statefulset --all-namespaces"
abbr --add kdstsall "kubecolor describe statefulset --all-namespaces"
abbr --add kgsvcall "kubecolor get service --all-namespaces"
abbr --add kdsvcall "kubecolor describe service --all-namespaces"
abbr --add kgingall "kubecolor get ingress --all-namespaces"
abbr --add kdingall "kubecolor describe ingress --all-namespaces"
abbr --add kgcmall "kubecolor get configmap --all-namespaces"
abbr --add kdcmall "kubecolor describe configmap --all-namespaces"
abbr --add kgsecall "kubecolor get secret --all-namespaces"
abbr --add kdsecall "kubecolor describe secret --all-namespaces"
abbr --add kgnsall "kubecolor get namespaces --all-namespaces"
abbr --add kdnsall "kubecolor describe namespaces --all-namespaces"
abbr --add kgsl "kubecolor get --show-labels"
abbr --add ksysgsl "kubecolor --namespace=kube-system get --show-labels"
abbr --add kgposl "kubecolor get pods --show-labels"
abbr --add ksysgposl "kubecolor --namespace=kube-system get pods --show-labels"
abbr --add kgdepsl "kubecolor get deployment --show-labels"
abbr --add ksysgdepsl "kubecolor --namespace=kube-system get deployment --show-labels"
abbr --add kgstssl "kubecolor get statefulset --show-labels"
abbr --add ksysgstssl "kubecolor --namespace=kube-system get statefulset --show-labels"
abbr --add kgsvcsl "kubecolor get service --show-labels"
abbr --add ksysgsvcsl "kubecolor --namespace=kube-system get service --show-labels"
abbr --add kgingsl "kubecolor get ingress --show-labels"
abbr --add ksysgingsl "kubecolor --namespace=kube-system get ingress --show-labels"
abbr --add kgcmsl "kubecolor get configmap --show-labels"
abbr --add ksysgcmsl "kubecolor --namespace=kube-system get configmap --show-labels"
abbr --add kgsecsl "kubecolor get secret --show-labels"
abbr --add ksysgsecsl "kubecolor --namespace=kube-system get secret --show-labels"
abbr --add kgnosl "kubecolor get nodes --show-labels"
abbr --add kgnssl "kubecolor get namespaces --show-labels"
abbr --add krmall "kubecolor delete --all"
abbr --add ksysrmall "kubecolor --namespace=kube-system delete --all"
abbr --add krmpoall "kubecolor delete pods --all"
abbr --add ksysrmpoall "kubecolor --namespace=kube-system delete pods --all"
abbr --add krmdepall "kubecolor delete deployment --all"
abbr --add ksysrmdepall "kubecolor --namespace=kube-system delete deployment --all"
abbr --add krmstsall "kubecolor delete statefulset --all"
abbr --add ksysrmstsall "kubecolor --namespace=kube-system delete statefulset --all"
abbr --add krmsvcall "kubecolor delete service --all"
abbr --add ksysrmsvcall "kubecolor --namespace=kube-system delete service --all"
abbr --add krmingall "kubecolor delete ingress --all"
abbr --add ksysrmingall "kubecolor --namespace=kube-system delete ingress --all"
abbr --add krmcmall "kubecolor delete configmap --all"
abbr --add ksysrmcmall "kubecolor --namespace=kube-system delete configmap --all"
abbr --add krmsecall "kubecolor delete secret --all"
abbr --add ksysrmsecall "kubecolor --namespace=kube-system delete secret --all"
abbr --add krmnsall "kubecolor delete namespaces --all"
abbr --add kgw "kubecolor get --watch"
abbr --add ksysgw "kubecolor --namespace=kube-system get --watch"
abbr --add kgpow "kubecolor get pods --watch"
abbr --add ksysgpow "kubecolor --namespace=kube-system get pods --watch"
abbr --add kgdepw "kubecolor get deployment --watch"
abbr --add ksysgdepw "kubecolor --namespace=kube-system get deployment --watch"
abbr --add kgstsw "kubecolor get statefulset --watch"
abbr --add ksysgstsw "kubecolor --namespace=kube-system get statefulset --watch"
abbr --add kgsvcw "kubecolor get service --watch"
abbr --add ksysgsvcw "kubecolor --namespace=kube-system get service --watch"
abbr --add kgingw "kubecolor get ingress --watch"
abbr --add ksysgingw "kubecolor --namespace=kube-system get ingress --watch"
abbr --add kgcmw "kubecolor get configmap --watch"
abbr --add ksysgcmw "kubecolor --namespace=kube-system get configmap --watch"
abbr --add kgsecw "kubecolor get secret --watch"
abbr --add ksysgsecw "kubecolor --namespace=kube-system get secret --watch"
abbr --add kgnow "kubecolor get nodes --watch"
abbr --add kgnsw "kubecolor get namespaces --watch"
abbr --add kgoyamlall "kubecolor get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "kubecolor get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "kubecolor get deployment -o=yaml --all-namespaces"
abbr --add kgstsoyamlall "kubecolor get statefulset -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "kubecolor get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "kubecolor get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "kubecolor get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "kubecolor get secret -o=yaml --all-namespaces"
abbr --add kgnsoyamlall "kubecolor get namespaces -o=yaml --all-namespaces"
abbr --add kgalloyaml "kubecolor get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "kubecolor get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "kubecolor get deployment --all-namespaces -o=yaml"
abbr --add kgstsalloyaml "kubecolor get statefulset --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "kubecolor get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "kubecolor get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "kubecolor get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "kubecolor get secret --all-namespaces -o=yaml"
abbr --add kgnsalloyaml "kubecolor get namespaces --all-namespaces -o=yaml"
abbr --add kgwoyaml "kubecolor get --watch -o=yaml"
abbr --add ksysgwoyaml "kubecolor --namespace=kube-system get --watch -o=yaml"
abbr --add kgpowoyaml "kubecolor get pods --watch -o=yaml"
abbr --add ksysgpowoyaml "kubecolor --namespace=kube-system get pods --watch -o=yaml"
abbr --add kgdepwoyaml "kubecolor get deployment --watch -o=yaml"
abbr --add ksysgdepwoyaml "kubecolor --namespace=kube-system get deployment --watch -o=yaml"
abbr --add kgstswoyaml "kubecolor get statefulset --watch -o=yaml"
abbr --add ksysgstswoyaml "kubecolor --namespace=kube-system get statefulset --watch -o=yaml"
abbr --add kgsvcwoyaml "kubecolor get service --watch -o=yaml"
abbr --add ksysgsvcwoyaml "kubecolor --namespace=kube-system get service --watch -o=yaml"
abbr --add kgingwoyaml "kubecolor get ingress --watch -o=yaml"
abbr --add ksysgingwoyaml "kubecolor --namespace=kube-system get ingress --watch -o=yaml"
abbr --add kgcmwoyaml "kubecolor get configmap --watch -o=yaml"
abbr --add ksysgcmwoyaml "kubecolor --namespace=kube-system get configmap --watch -o=yaml"
abbr --add kgsecwoyaml "kubecolor get secret --watch -o=yaml"
abbr --add ksysgsecwoyaml "kubecolor --namespace=kube-system get secret --watch -o=yaml"
abbr --add kgnowoyaml "kubecolor get nodes --watch -o=yaml"
abbr --add kgnswoyaml "kubecolor get namespaces --watch -o=yaml"
abbr --add kgowideall "kubecolor get -o=wide --all-namespaces"
abbr --add kgpoowideall "kubecolor get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "kubecolor get deployment -o=wide --all-namespaces"
abbr --add kgstsowideall "kubecolor get statefulset -o=wide --all-namespaces"
abbr --add kgsvcowideall "kubecolor get service -o=wide --all-namespaces"
abbr --add kgingowideall "kubecolor get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "kubecolor get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "kubecolor get secret -o=wide --all-namespaces"
abbr --add kgnsowideall "kubecolor get namespaces -o=wide --all-namespaces"
abbr --add kgallowide "kubecolor get --all-namespaces -o=wide"
abbr --add kgpoallowide "kubecolor get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "kubecolor get deployment --all-namespaces -o=wide"
abbr --add kgstsallowide "kubecolor get statefulset --all-namespaces -o=wide"
abbr --add kgsvcallowide "kubecolor get service --all-namespaces -o=wide"
abbr --add kgingallowide "kubecolor get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "kubecolor get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "kubecolor get secret --all-namespaces -o=wide"
abbr --add kgnsallowide "kubecolor get namespaces --all-namespaces -o=wide"
abbr --add kgowidesl "kubecolor get -o=wide --show-labels"
abbr --add ksysgowidesl "kubecolor --namespace=kube-system get -o=wide --show-labels"
abbr --add kgpoowidesl "kubecolor get pods -o=wide --show-labels"
abbr --add ksysgpoowidesl "kubecolor --namespace=kube-system get pods -o=wide --show-labels"
abbr --add kgdepowidesl "kubecolor get deployment -o=wide --show-labels"
abbr --add ksysgdepowidesl "kubecolor --namespace=kube-system get deployment -o=wide --show-labels"
abbr --add kgstsowidesl "kubecolor get statefulset -o=wide --show-labels"
abbr --add ksysgstsowidesl "kubecolor --namespace=kube-system get statefulset -o=wide --show-labels"
abbr --add kgsvcowidesl "kubecolor get service -o=wide --show-labels"
abbr --add ksysgsvcowidesl "kubecolor --namespace=kube-system get service -o=wide --show-labels"
abbr --add kgingowidesl "kubecolor get ingress -o=wide --show-labels"
abbr --add ksysgingowidesl "kubecolor --namespace=kube-system get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "kubecolor get configmap -o=wide --show-labels"
abbr --add ksysgcmowidesl "kubecolor --namespace=kube-system get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "kubecolor get secret -o=wide --show-labels"
abbr --add ksysgsecowidesl "kubecolor --namespace=kube-system get secret -o=wide --show-labels"
abbr --add kgnoowidesl "kubecolor get nodes -o=wide --show-labels"
abbr --add kgnsowidesl "kubecolor get namespaces -o=wide --show-labels"
abbr --add kgslowide "kubecolor get --show-labels -o=wide"
abbr --add ksysgslowide "kubecolor --namespace=kube-system get --show-labels -o=wide"
abbr --add kgposlowide "kubecolor get pods --show-labels -o=wide"
abbr --add ksysgposlowide "kubecolor --namespace=kube-system get pods --show-labels -o=wide"
abbr --add kgdepslowide "kubecolor get deployment --show-labels -o=wide"
abbr --add ksysgdepslowide "kubecolor --namespace=kube-system get deployment --show-labels -o=wide"
abbr --add kgstsslowide "kubecolor get statefulset --show-labels -o=wide"
abbr --add ksysgstsslowide "kubecolor --namespace=kube-system get statefulset --show-labels -o=wide"
abbr --add kgsvcslowide "kubecolor get service --show-labels -o=wide"
abbr --add ksysgsvcslowide "kubecolor --namespace=kube-system get service --show-labels -o=wide"
abbr --add kgingslowide "kubecolor get ingress --show-labels -o=wide"
abbr --add ksysgingslowide "kubecolor --namespace=kube-system get ingress --show-labels -o=wide"
abbr --add kgcmslowide "kubecolor get configmap --show-labels -o=wide"
abbr --add ksysgcmslowide "kubecolor --namespace=kube-system get configmap --show-labels -o=wide"
abbr --add kgsecslowide "kubecolor get secret --show-labels -o=wide"
abbr --add ksysgsecslowide "kubecolor --namespace=kube-system get secret --show-labels -o=wide"
abbr --add kgnoslowide "kubecolor get nodes --show-labels -o=wide"
abbr --add kgnsslowide "kubecolor get namespaces --show-labels -o=wide"
abbr --add kgwowide "kubecolor get --watch -o=wide"
abbr --add ksysgwowide "kubecolor --namespace=kube-system get --watch -o=wide"
abbr --add kgpowowide "kubecolor get pods --watch -o=wide"
abbr --add ksysgpowowide "kubecolor --namespace=kube-system get pods --watch -o=wide"
abbr --add kgdepwowide "kubecolor get deployment --watch -o=wide"
abbr --add ksysgdepwowide "kubecolor --namespace=kube-system get deployment --watch -o=wide"
abbr --add kgstswowide "kubecolor get statefulset --watch -o=wide"
abbr --add ksysgstswowide "kubecolor --namespace=kube-system get statefulset --watch -o=wide"
abbr --add kgsvcwowide "kubecolor get service --watch -o=wide"
abbr --add ksysgsvcwowide "kubecolor --namespace=kube-system get service --watch -o=wide"
abbr --add kgingwowide "kubecolor get ingress --watch -o=wide"
abbr --add ksysgingwowide "kubecolor --namespace=kube-system get ingress --watch -o=wide"
abbr --add kgcmwowide "kubecolor get configmap --watch -o=wide"
abbr --add ksysgcmwowide "kubecolor --namespace=kube-system get configmap --watch -o=wide"
abbr --add kgsecwowide "kubecolor get secret --watch -o=wide"
abbr --add ksysgsecwowide "kubecolor --namespace=kube-system get secret --watch -o=wide"
abbr --add kgnowowide "kubecolor get nodes --watch -o=wide"
abbr --add kgnswowide "kubecolor get namespaces --watch -o=wide"
abbr --add kgojsonall "kubecolor get -o=json --all-namespaces"
abbr --add kgpoojsonall "kubecolor get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "kubecolor get deployment -o=json --all-namespaces"
abbr --add kgstsojsonall "kubecolor get statefulset -o=json --all-namespaces"
abbr --add kgsvcojsonall "kubecolor get service -o=json --all-namespaces"
abbr --add kgingojsonall "kubecolor get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "kubecolor get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "kubecolor get secret -o=json --all-namespaces"
abbr --add kgnsojsonall "kubecolor get namespaces -o=json --all-namespaces"
abbr --add kgallojson "kubecolor get --all-namespaces -o=json"
abbr --add kgpoallojson "kubecolor get pods --all-namespaces -o=json"
abbr --add kgdepallojson "kubecolor get deployment --all-namespaces -o=json"
abbr --add kgstsallojson "kubecolor get statefulset --all-namespaces -o=json"
abbr --add kgsvcallojson "kubecolor get service --all-namespaces -o=json"
abbr --add kgingallojson "kubecolor get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "kubecolor get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "kubecolor get secret --all-namespaces -o=json"
abbr --add kgnsallojson "kubecolor get namespaces --all-namespaces -o=json"
abbr --add kgwojson "kubecolor get --watch -o=json"
abbr --add ksysgwojson "kubecolor --namespace=kube-system get --watch -o=json"
abbr --add kgpowojson "kubecolor get pods --watch -o=json"
abbr --add ksysgpowojson "kubecolor --namespace=kube-system get pods --watch -o=json"
abbr --add kgdepwojson "kubecolor get deployment --watch -o=json"
abbr --add ksysgdepwojson "kubecolor --namespace=kube-system get deployment --watch -o=json"
abbr --add kgstswojson "kubecolor get statefulset --watch -o=json"
abbr --add ksysgstswojson "kubecolor --namespace=kube-system get statefulset --watch -o=json"
abbr --add kgsvcwojson "kubecolor get service --watch -o=json"
abbr --add ksysgsvcwojson "kubecolor --namespace=kube-system get service --watch -o=json"
abbr --add kgingwojson "kubecolor get ingress --watch -o=json"
abbr --add ksysgingwojson "kubecolor --namespace=kube-system get ingress --watch -o=json"
abbr --add kgcmwojson "kubecolor get configmap --watch -o=json"
abbr --add ksysgcmwojson "kubecolor --namespace=kube-system get configmap --watch -o=json"
abbr --add kgsecwojson "kubecolor get secret --watch -o=json"
abbr --add ksysgsecwojson "kubecolor --namespace=kube-system get secret --watch -o=json"
abbr --add kgnowojson "kubecolor get nodes --watch -o=json"
abbr --add kgnswojson "kubecolor get namespaces --watch -o=json"
abbr --add kgallsl "kubecolor get --all-namespaces --show-labels"
abbr --add kgpoallsl "kubecolor get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "kubecolor get deployment --all-namespaces --show-labels"
abbr --add kgstsallsl "kubecolor get statefulset --all-namespaces --show-labels"
abbr --add kgsvcallsl "kubecolor get service --all-namespaces --show-labels"
abbr --add kgingallsl "kubecolor get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "kubecolor get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "kubecolor get secret --all-namespaces --show-labels"
abbr --add kgnsallsl "kubecolor get namespaces --all-namespaces --show-labels"
abbr --add kgslall "kubecolor get --show-labels --all-namespaces"
abbr --add kgposlall "kubecolor get pods --show-labels --all-namespaces"
abbr --add kgdepslall "kubecolor get deployment --show-labels --all-namespaces"
abbr --add kgstsslall "kubecolor get statefulset --show-labels --all-namespaces"
abbr --add kgsvcslall "kubecolor get service --show-labels --all-namespaces"
abbr --add kgingslall "kubecolor get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "kubecolor get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "kubecolor get secret --show-labels --all-namespaces"
abbr --add kgnsslall "kubecolor get namespaces --show-labels --all-namespaces"
abbr --add kgallw "kubecolor get --all-namespaces --watch"
abbr --add kgpoallw "kubecolor get pods --all-namespaces --watch"
abbr --add kgdepallw "kubecolor get deployment --all-namespaces --watch"
abbr --add kgstsallw "kubecolor get statefulset --all-namespaces --watch"
abbr --add kgsvcallw "kubecolor get service --all-namespaces --watch"
abbr --add kgingallw "kubecolor get ingress --all-namespaces --watch"
abbr --add kgcmallw "kubecolor get configmap --all-namespaces --watch"
abbr --add kgsecallw "kubecolor get secret --all-namespaces --watch"
abbr --add kgnsallw "kubecolor get namespaces --all-namespaces --watch"
abbr --add kgwall "kubecolor get --watch --all-namespaces"
abbr --add kgpowall "kubecolor get pods --watch --all-namespaces"
abbr --add kgdepwall "kubecolor get deployment --watch --all-namespaces"
abbr --add kgstswall "kubecolor get statefulset --watch --all-namespaces"
abbr --add kgsvcwall "kubecolor get service --watch --all-namespaces"
abbr --add kgingwall "kubecolor get ingress --watch --all-namespaces"
abbr --add kgcmwall "kubecolor get configmap --watch --all-namespaces"
abbr --add kgsecwall "kubecolor get secret --watch --all-namespaces"
abbr --add kgnswall "kubecolor get namespaces --watch --all-namespaces"
abbr --add kgslw "kubecolor get --show-labels --watch"
abbr --add ksysgslw "kubecolor --namespace=kube-system get --show-labels --watch"
abbr --add kgposlw "kubecolor get pods --show-labels --watch"
abbr --add ksysgposlw "kubecolor --namespace=kube-system get pods --show-labels --watch"
abbr --add kgdepslw "kubecolor get deployment --show-labels --watch"
abbr --add ksysgdepslw "kubecolor --namespace=kube-system get deployment --show-labels --watch"
abbr --add kgstsslw "kubecolor get statefulset --show-labels --watch"
abbr --add ksysgstsslw "kubecolor --namespace=kube-system get statefulset --show-labels --watch"
abbr --add kgsvcslw "kubecolor get service --show-labels --watch"
abbr --add ksysgsvcslw "kubecolor --namespace=kube-system get service --show-labels --watch"
abbr --add kgingslw "kubecolor get ingress --show-labels --watch"
abbr --add ksysgingslw "kubecolor --namespace=kube-system get ingress --show-labels --watch"
abbr --add kgcmslw "kubecolor get configmap --show-labels --watch"
abbr --add ksysgcmslw "kubecolor --namespace=kube-system get configmap --show-labels --watch"
abbr --add kgsecslw "kubecolor get secret --show-labels --watch"
abbr --add ksysgsecslw "kubecolor --namespace=kube-system get secret --show-labels --watch"
abbr --add kgnoslw "kubecolor get nodes --show-labels --watch"
abbr --add kgnsslw "kubecolor get namespaces --show-labels --watch"
abbr --add kgwsl "kubecolor get --watch --show-labels"
abbr --add ksysgwsl "kubecolor --namespace=kube-system get --watch --show-labels"
abbr --add kgpowsl "kubecolor get pods --watch --show-labels"
abbr --add ksysgpowsl "kubecolor --namespace=kube-system get pods --watch --show-labels"
abbr --add kgdepwsl "kubecolor get deployment --watch --show-labels"
abbr --add ksysgdepwsl "kubecolor --namespace=kube-system get deployment --watch --show-labels"
abbr --add kgstswsl "kubecolor get statefulset --watch --show-labels"
abbr --add ksysgstswsl "kubecolor --namespace=kube-system get statefulset --watch --show-labels"
abbr --add kgsvcwsl "kubecolor get service --watch --show-labels"
abbr --add ksysgsvcwsl "kubecolor --namespace=kube-system get service --watch --show-labels"
abbr --add kgingwsl "kubecolor get ingress --watch --show-labels"
abbr --add ksysgingwsl "kubecolor --namespace=kube-system get ingress --watch --show-labels"
abbr --add kgcmwsl "kubecolor get configmap --watch --show-labels"
abbr --add ksysgcmwsl "kubecolor --namespace=kube-system get configmap --watch --show-labels"
abbr --add kgsecwsl "kubecolor get secret --watch --show-labels"
abbr --add ksysgsecwsl "kubecolor --namespace=kube-system get secret --watch --show-labels"
abbr --add kgnowsl "kubecolor get nodes --watch --show-labels"
abbr --add kgnswsl "kubecolor get namespaces --watch --show-labels"
abbr --add kgallwoyaml "kubecolor get --all-namespaces --watch -o=yaml"
abbr --add kgpoallwoyaml "kubecolor get pods --all-namespaces --watch -o=yaml"
abbr --add kgdepallwoyaml "kubecolor get deployment --all-namespaces --watch -o=yaml"
abbr --add kgstsallwoyaml "kubecolor get statefulset --all-namespaces --watch -o=yaml"
abbr --add kgsvcallwoyaml "kubecolor get service --all-namespaces --watch -o=yaml"
abbr --add kgingallwoyaml "kubecolor get ingress --all-namespaces --watch -o=yaml"
abbr --add kgcmallwoyaml "kubecolor get configmap --all-namespaces --watch -o=yaml"
abbr --add kgsecallwoyaml "kubecolor get secret --all-namespaces --watch -o=yaml"
abbr --add kgnsallwoyaml "kubecolor get namespaces --all-namespaces --watch -o=yaml"
abbr --add kgwoyamlall "kubecolor get --watch -o=yaml --all-namespaces"
abbr --add kgpowoyamlall "kubecolor get pods --watch -o=yaml --all-namespaces"
abbr --add kgdepwoyamlall "kubecolor get deployment --watch -o=yaml --all-namespaces"
abbr --add kgstswoyamlall "kubecolor get statefulset --watch -o=yaml --all-namespaces"
abbr --add kgsvcwoyamlall "kubecolor get service --watch -o=yaml --all-namespaces"
abbr --add kgingwoyamlall "kubecolor get ingress --watch -o=yaml --all-namespaces"
abbr --add kgcmwoyamlall "kubecolor get configmap --watch -o=yaml --all-namespaces"
abbr --add kgsecwoyamlall "kubecolor get secret --watch -o=yaml --all-namespaces"
abbr --add kgnswoyamlall "kubecolor get namespaces --watch -o=yaml --all-namespaces"
abbr --add kgwalloyaml "kubecolor get --watch --all-namespaces -o=yaml"
abbr --add kgpowalloyaml "kubecolor get pods --watch --all-namespaces -o=yaml"
abbr --add kgdepwalloyaml "kubecolor get deployment --watch --all-namespaces -o=yaml"
abbr --add kgstswalloyaml "kubecolor get statefulset --watch --all-namespaces -o=yaml"
abbr --add kgsvcwalloyaml "kubecolor get service --watch --all-namespaces -o=yaml"
abbr --add kgingwalloyaml "kubecolor get ingress --watch --all-namespaces -o=yaml"
abbr --add kgcmwalloyaml "kubecolor get configmap --watch --all-namespaces -o=yaml"
abbr --add kgsecwalloyaml "kubecolor get secret --watch --all-namespaces -o=yaml"
abbr --add kgnswalloyaml "kubecolor get namespaces --watch --all-namespaces -o=yaml"
abbr --add kgowideallsl "kubecolor get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "kubecolor get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "kubecolor get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgstsowideallsl "kubecolor get statefulset -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "kubecolor get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "kubecolor get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "kubecolor get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "kubecolor get secret -o=wide --all-namespaces --show-labels"
abbr --add kgnsowideallsl "kubecolor get namespaces -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "kubecolor get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "kubecolor get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "kubecolor get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgstsowideslall "kubecolor get statefulset -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "kubecolor get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "kubecolor get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "kubecolor get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "kubecolor get secret -o=wide --show-labels --all-namespaces"
abbr --add kgnsowideslall "kubecolor get namespaces -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "kubecolor get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "kubecolor get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "kubecolor get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgstsallowidesl "kubecolor get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "kubecolor get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "kubecolor get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "kubecolor get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "kubecolor get secret --all-namespaces -o=wide --show-labels"
abbr --add kgnsallowidesl "kubecolor get namespaces --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "kubecolor get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "kubecolor get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "kubecolor get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgstsallslowide "kubecolor get statefulset --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "kubecolor get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "kubecolor get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "kubecolor get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "kubecolor get secret --all-namespaces --show-labels -o=wide"
abbr --add kgnsallslowide "kubecolor get namespaces --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "kubecolor get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "kubecolor get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "kubecolor get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgstsslowideall "kubecolor get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "kubecolor get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "kubecolor get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "kubecolor get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "kubecolor get secret --show-labels -o=wide --all-namespaces"
abbr --add kgnsslowideall "kubecolor get namespaces --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "kubecolor get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "kubecolor get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "kubecolor get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgstsslallowide "kubecolor get statefulset --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "kubecolor get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "kubecolor get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "kubecolor get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "kubecolor get secret --show-labels --all-namespaces -o=wide"
abbr --add kgnsslallowide "kubecolor get namespaces --show-labels --all-namespaces -o=wide"
abbr --add kgallwowide "kubecolor get --all-namespaces --watch -o=wide"
abbr --add kgpoallwowide "kubecolor get pods --all-namespaces --watch -o=wide"
abbr --add kgdepallwowide "kubecolor get deployment --all-namespaces --watch -o=wide"
abbr --add kgstsallwowide "kubecolor get statefulset --all-namespaces --watch -o=wide"
abbr --add kgsvcallwowide "kubecolor get service --all-namespaces --watch -o=wide"
abbr --add kgingallwowide "kubecolor get ingress --all-namespaces --watch -o=wide"
abbr --add kgcmallwowide "kubecolor get configmap --all-namespaces --watch -o=wide"
abbr --add kgsecallwowide "kubecolor get secret --all-namespaces --watch -o=wide"
abbr --add kgnsallwowide "kubecolor get namespaces --all-namespaces --watch -o=wide"
abbr --add kgwowideall "kubecolor get --watch -o=wide --all-namespaces"
abbr --add kgpowowideall "kubecolor get pods --watch -o=wide --all-namespaces"
abbr --add kgdepwowideall "kubecolor get deployment --watch -o=wide --all-namespaces"
abbr --add kgstswowideall "kubecolor get statefulset --watch -o=wide --all-namespaces"
abbr --add kgsvcwowideall "kubecolor get service --watch -o=wide --all-namespaces"
abbr --add kgingwowideall "kubecolor get ingress --watch -o=wide --all-namespaces"
abbr --add kgcmwowideall "kubecolor get configmap --watch -o=wide --all-namespaces"
abbr --add kgsecwowideall "kubecolor get secret --watch -o=wide --all-namespaces"
abbr --add kgnswowideall "kubecolor get namespaces --watch -o=wide --all-namespaces"
abbr --add kgwallowide "kubecolor get --watch --all-namespaces -o=wide"
abbr --add kgpowallowide "kubecolor get pods --watch --all-namespaces -o=wide"
abbr --add kgdepwallowide "kubecolor get deployment --watch --all-namespaces -o=wide"
abbr --add kgstswallowide "kubecolor get statefulset --watch --all-namespaces -o=wide"
abbr --add kgsvcwallowide "kubecolor get service --watch --all-namespaces -o=wide"
abbr --add kgingwallowide "kubecolor get ingress --watch --all-namespaces -o=wide"
abbr --add kgcmwallowide "kubecolor get configmap --watch --all-namespaces -o=wide"
abbr --add kgsecwallowide "kubecolor get secret --watch --all-namespaces -o=wide"
abbr --add kgnswallowide "kubecolor get namespaces --watch --all-namespaces -o=wide"
abbr --add kgslwowide "kubecolor get --show-labels --watch -o=wide"
abbr --add ksysgslwowide "kubecolor --namespace=kube-system get --show-labels --watch -o=wide"
abbr --add kgposlwowide "kubecolor get pods --show-labels --watch -o=wide"
abbr --add ksysgposlwowide "kubecolor --namespace=kube-system get pods --show-labels --watch -o=wide"
abbr --add kgdepslwowide "kubecolor get deployment --show-labels --watch -o=wide"
abbr --add ksysgdepslwowide "kubecolor --namespace=kube-system get deployment --show-labels --watch -o=wide"
abbr --add kgstsslwowide "kubecolor get statefulset --show-labels --watch -o=wide"
abbr --add ksysgstsslwowide "kubecolor --namespace=kube-system get statefulset --show-labels --watch -o=wide"
abbr --add kgsvcslwowide "kubecolor get service --show-labels --watch -o=wide"
abbr --add ksysgsvcslwowide "kubecolor --namespace=kube-system get service --show-labels --watch -o=wide"
abbr --add kgingslwowide "kubecolor get ingress --show-labels --watch -o=wide"
abbr --add ksysgingslwowide "kubecolor --namespace=kube-system get ingress --show-labels --watch -o=wide"
abbr --add kgcmslwowide "kubecolor get configmap --show-labels --watch -o=wide"
abbr --add ksysgcmslwowide "kubecolor --namespace=kube-system get configmap --show-labels --watch -o=wide"
abbr --add kgsecslwowide "kubecolor get secret --show-labels --watch -o=wide"
abbr --add ksysgsecslwowide "kubecolor --namespace=kube-system get secret --show-labels --watch -o=wide"
abbr --add kgnoslwowide "kubecolor get nodes --show-labels --watch -o=wide"
abbr --add kgnsslwowide "kubecolor get namespaces --show-labels --watch -o=wide"
abbr --add kgwowidesl "kubecolor get --watch -o=wide --show-labels"
abbr --add ksysgwowidesl "kubecolor --namespace=kube-system get --watch -o=wide --show-labels"
abbr --add kgpowowidesl "kubecolor get pods --watch -o=wide --show-labels"
abbr --add ksysgpowowidesl "kubecolor --namespace=kube-system get pods --watch -o=wide --show-labels"
abbr --add kgdepwowidesl "kubecolor get deployment --watch -o=wide --show-labels"
abbr --add ksysgdepwowidesl "kubecolor --namespace=kube-system get deployment --watch -o=wide --show-labels"
abbr --add kgstswowidesl "kubecolor get statefulset --watch -o=wide --show-labels"
abbr --add ksysgstswowidesl "kubecolor --namespace=kube-system get statefulset --watch -o=wide --show-labels"
abbr --add kgsvcwowidesl "kubecolor get service --watch -o=wide --show-labels"
abbr --add ksysgsvcwowidesl "kubecolor --namespace=kube-system get service --watch -o=wide --show-labels"
abbr --add kgingwowidesl "kubecolor get ingress --watch -o=wide --show-labels"
abbr --add ksysgingwowidesl "kubecolor --namespace=kube-system get ingress --watch -o=wide --show-labels"
abbr --add kgcmwowidesl "kubecolor get configmap --watch -o=wide --show-labels"
abbr --add ksysgcmwowidesl "kubecolor --namespace=kube-system get configmap --watch -o=wide --show-labels"
abbr --add kgsecwowidesl "kubecolor get secret --watch -o=wide --show-labels"
abbr --add ksysgsecwowidesl "kubecolor --namespace=kube-system get secret --watch -o=wide --show-labels"
abbr --add kgnowowidesl "kubecolor get nodes --watch -o=wide --show-labels"
abbr --add kgnswowidesl "kubecolor get namespaces --watch -o=wide --show-labels"
abbr --add kgwslowide "kubecolor get --watch --show-labels -o=wide"
abbr --add ksysgwslowide "kubecolor --namespace=kube-system get --watch --show-labels -o=wide"
abbr --add kgpowslowide "kubecolor get pods --watch --show-labels -o=wide"
abbr --add ksysgpowslowide "kubecolor --namespace=kube-system get pods --watch --show-labels -o=wide"
abbr --add kgdepwslowide "kubecolor get deployment --watch --show-labels -o=wide"
abbr --add ksysgdepwslowide "kubecolor --namespace=kube-system get deployment --watch --show-labels -o=wide"
abbr --add kgstswslowide "kubecolor get statefulset --watch --show-labels -o=wide"
abbr --add ksysgstswslowide "kubecolor --namespace=kube-system get statefulset --watch --show-labels -o=wide"
abbr --add kgsvcwslowide "kubecolor get service --watch --show-labels -o=wide"
abbr --add ksysgsvcwslowide "kubecolor --namespace=kube-system get service --watch --show-labels -o=wide"
abbr --add kgingwslowide "kubecolor get ingress --watch --show-labels -o=wide"
abbr --add ksysgingwslowide "kubecolor --namespace=kube-system get ingress --watch --show-labels -o=wide"
abbr --add kgcmwslowide "kubecolor get configmap --watch --show-labels -o=wide"
abbr --add ksysgcmwslowide "kubecolor --namespace=kube-system get configmap --watch --show-labels -o=wide"
abbr --add kgsecwslowide "kubecolor get secret --watch --show-labels -o=wide"
abbr --add ksysgsecwslowide "kubecolor --namespace=kube-system get secret --watch --show-labels -o=wide"
abbr --add kgnowslowide "kubecolor get nodes --watch --show-labels -o=wide"
abbr --add kgnswslowide "kubecolor get namespaces --watch --show-labels -o=wide"
abbr --add kgallwojson "kubecolor get --all-namespaces --watch -o=json"
abbr --add kgpoallwojson "kubecolor get pods --all-namespaces --watch -o=json"
abbr --add kgdepallwojson "kubecolor get deployment --all-namespaces --watch -o=json"
abbr --add kgstsallwojson "kubecolor get statefulset --all-namespaces --watch -o=json"
abbr --add kgsvcallwojson "kubecolor get service --all-namespaces --watch -o=json"
abbr --add kgingallwojson "kubecolor get ingress --all-namespaces --watch -o=json"
abbr --add kgcmallwojson "kubecolor get configmap --all-namespaces --watch -o=json"
abbr --add kgsecallwojson "kubecolor get secret --all-namespaces --watch -o=json"
abbr --add kgnsallwojson "kubecolor get namespaces --all-namespaces --watch -o=json"
abbr --add kgwojsonall "kubecolor get --watch -o=json --all-namespaces"
abbr --add kgpowojsonall "kubecolor get pods --watch -o=json --all-namespaces"
abbr --add kgdepwojsonall "kubecolor get deployment --watch -o=json --all-namespaces"
abbr --add kgstswojsonall "kubecolor get statefulset --watch -o=json --all-namespaces"
abbr --add kgsvcwojsonall "kubecolor get service --watch -o=json --all-namespaces"
abbr --add kgingwojsonall "kubecolor get ingress --watch -o=json --all-namespaces"
abbr --add kgcmwojsonall "kubecolor get configmap --watch -o=json --all-namespaces"
abbr --add kgsecwojsonall "kubecolor get secret --watch -o=json --all-namespaces"
abbr --add kgnswojsonall "kubecolor get namespaces --watch -o=json --all-namespaces"
abbr --add kgwallojson "kubecolor get --watch --all-namespaces -o=json"
abbr --add kgpowallojson "kubecolor get pods --watch --all-namespaces -o=json"
abbr --add kgdepwallojson "kubecolor get deployment --watch --all-namespaces -o=json"
abbr --add kgstswallojson "kubecolor get statefulset --watch --all-namespaces -o=json"
abbr --add kgsvcwallojson "kubecolor get service --watch --all-namespaces -o=json"
abbr --add kgingwallojson "kubecolor get ingress --watch --all-namespaces -o=json"
abbr --add kgcmwallojson "kubecolor get configmap --watch --all-namespaces -o=json"
abbr --add kgsecwallojson "kubecolor get secret --watch --all-namespaces -o=json"
abbr --add kgnswallojson "kubecolor get namespaces --watch --all-namespaces -o=json"
abbr --add kgallslw "kubecolor get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "kubecolor get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "kubecolor get deployment --all-namespaces --show-labels --watch"
abbr --add kgstsallslw "kubecolor get statefulset --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "kubecolor get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "kubecolor get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "kubecolor get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "kubecolor get secret --all-namespaces --show-labels --watch"
abbr --add kgnsallslw "kubecolor get namespaces --all-namespaces --show-labels --watch"
abbr --add kgallwsl "kubecolor get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "kubecolor get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "kubecolor get deployment --all-namespaces --watch --show-labels"
abbr --add kgstsallwsl "kubecolor get statefulset --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "kubecolor get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "kubecolor get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "kubecolor get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "kubecolor get secret --all-namespaces --watch --show-labels"
abbr --add kgnsallwsl "kubecolor get namespaces --all-namespaces --watch --show-labels"
abbr --add kgslallw "kubecolor get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "kubecolor get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "kubecolor get deployment --show-labels --all-namespaces --watch"
abbr --add kgstsslallw "kubecolor get statefulset --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "kubecolor get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "kubecolor get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "kubecolor get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "kubecolor get secret --show-labels --all-namespaces --watch"
abbr --add kgnsslallw "kubecolor get namespaces --show-labels --all-namespaces --watch"
abbr --add kgslwall "kubecolor get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "kubecolor get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "kubecolor get deployment --show-labels --watch --all-namespaces"
abbr --add kgstsslwall "kubecolor get statefulset --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "kubecolor get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "kubecolor get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "kubecolor get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "kubecolor get secret --show-labels --watch --all-namespaces"
abbr --add kgnsslwall "kubecolor get namespaces --show-labels --watch --all-namespaces"
abbr --add kgwallsl "kubecolor get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "kubecolor get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "kubecolor get deployment --watch --all-namespaces --show-labels"
abbr --add kgstswallsl "kubecolor get statefulset --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "kubecolor get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "kubecolor get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "kubecolor get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "kubecolor get secret --watch --all-namespaces --show-labels"
abbr --add kgnswallsl "kubecolor get namespaces --watch --all-namespaces --show-labels"
abbr --add kgwslall "kubecolor get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "kubecolor get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "kubecolor get deployment --watch --show-labels --all-namespaces"
abbr --add kgstswslall "kubecolor get statefulset --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "kubecolor get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "kubecolor get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "kubecolor get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "kubecolor get secret --watch --show-labels --all-namespaces"
abbr --add kgnswslall "kubecolor get namespaces --watch --show-labels --all-namespaces"
abbr --add kgallslwowide "kubecolor get --all-namespaces --show-labels --watch -o=wide"
abbr --add kgpoallslwowide "kubecolor get pods --all-namespaces --show-labels --watch -o=wide"
abbr --add kgdepallslwowide "kubecolor get deployment --all-namespaces --show-labels --watch -o=wide"
abbr --add kgstsallslwowide "kubecolor get statefulset --all-namespaces --show-labels --watch -o=wide"
abbr --add kgsvcallslwowide "kubecolor get service --all-namespaces --show-labels --watch -o=wide"
abbr --add kgingallslwowide "kubecolor get ingress --all-namespaces --show-labels --watch -o=wide"
abbr --add kgcmallslwowide "kubecolor get configmap --all-namespaces --show-labels --watch -o=wide"
abbr --add kgsecallslwowide "kubecolor get secret --all-namespaces --show-labels --watch -o=wide"
abbr --add kgnsallslwowide "kubecolor get namespaces --all-namespaces --show-labels --watch -o=wide"
abbr --add kgallwowidesl "kubecolor get --all-namespaces --watch -o=wide --show-labels"
abbr --add kgpoallwowidesl "kubecolor get pods --all-namespaces --watch -o=wide --show-labels"
abbr --add kgdepallwowidesl "kubecolor get deployment --all-namespaces --watch -o=wide --show-labels"
abbr --add kgstsallwowidesl "kubecolor get statefulset --all-namespaces --watch -o=wide --show-labels"
abbr --add kgsvcallwowidesl "kubecolor get service --all-namespaces --watch -o=wide --show-labels"
abbr --add kgingallwowidesl "kubecolor get ingress --all-namespaces --watch -o=wide --show-labels"
abbr --add kgcmallwowidesl "kubecolor get configmap --all-namespaces --watch -o=wide --show-labels"
abbr --add kgsecallwowidesl "kubecolor get secret --all-namespaces --watch -o=wide --show-labels"
abbr --add kgnsallwowidesl "kubecolor get namespaces --all-namespaces --watch -o=wide --show-labels"
abbr --add kgallwslowide "kubecolor get --all-namespaces --watch --show-labels -o=wide"
abbr --add kgpoallwslowide "kubecolor get pods --all-namespaces --watch --show-labels -o=wide"
abbr --add kgdepallwslowide "kubecolor get deployment --all-namespaces --watch --show-labels -o=wide"
abbr --add kgstsallwslowide "kubecolor get statefulset --all-namespaces --watch --show-labels -o=wide"
abbr --add kgsvcallwslowide "kubecolor get service --all-namespaces --watch --show-labels -o=wide"
abbr --add kgingallwslowide "kubecolor get ingress --all-namespaces --watch --show-labels -o=wide"
abbr --add kgcmallwslowide "kubecolor get configmap --all-namespaces --watch --show-labels -o=wide"
abbr --add kgsecallwslowide "kubecolor get secret --all-namespaces --watch --show-labels -o=wide"
abbr --add kgnsallwslowide "kubecolor get namespaces --all-namespaces --watch --show-labels -o=wide"
abbr --add kgslallwowide "kubecolor get --show-labels --all-namespaces --watch -o=wide"
abbr --add kgposlallwowide "kubecolor get pods --show-labels --all-namespaces --watch -o=wide"
abbr --add kgdepslallwowide "kubecolor get deployment --show-labels --all-namespaces --watch -o=wide"
abbr --add kgstsslallwowide "kubecolor get statefulset --show-labels --all-namespaces --watch -o=wide"
abbr --add kgsvcslallwowide "kubecolor get service --show-labels --all-namespaces --watch -o=wide"
abbr --add kgingslallwowide "kubecolor get ingress --show-labels --all-namespaces --watch -o=wide"
abbr --add kgcmslallwowide "kubecolor get configmap --show-labels --all-namespaces --watch -o=wide"
abbr --add kgsecslallwowide "kubecolor get secret --show-labels --all-namespaces --watch -o=wide"
abbr --add kgnsslallwowide "kubecolor get namespaces --show-labels --all-namespaces --watch -o=wide"
abbr --add kgslwowideall "kubecolor get --show-labels --watch -o=wide --all-namespaces"
abbr --add kgposlwowideall "kubecolor get pods --show-labels --watch -o=wide --all-namespaces"
abbr --add kgdepslwowideall "kubecolor get deployment --show-labels --watch -o=wide --all-namespaces"
abbr --add kgstsslwowideall "kubecolor get statefulset --show-labels --watch -o=wide --all-namespaces"
abbr --add kgsvcslwowideall "kubecolor get service --show-labels --watch -o=wide --all-namespaces"
abbr --add kgingslwowideall "kubecolor get ingress --show-labels --watch -o=wide --all-namespaces"
abbr --add kgcmslwowideall "kubecolor get configmap --show-labels --watch -o=wide --all-namespaces"
abbr --add kgsecslwowideall "kubecolor get secret --show-labels --watch -o=wide --all-namespaces"
abbr --add kgnsslwowideall "kubecolor get namespaces --show-labels --watch -o=wide --all-namespaces"
abbr --add kgslwallowide "kubecolor get --show-labels --watch --all-namespaces -o=wide"
abbr --add kgposlwallowide "kubecolor get pods --show-labels --watch --all-namespaces -o=wide"
abbr --add kgdepslwallowide "kubecolor get deployment --show-labels --watch --all-namespaces -o=wide"
abbr --add kgstsslwallowide "kubecolor get statefulset --show-labels --watch --all-namespaces -o=wide"
abbr --add kgsvcslwallowide "kubecolor get service --show-labels --watch --all-namespaces -o=wide"
abbr --add kgingslwallowide "kubecolor get ingress --show-labels --watch --all-namespaces -o=wide"
abbr --add kgcmslwallowide "kubecolor get configmap --show-labels --watch --all-namespaces -o=wide"
abbr --add kgsecslwallowide "kubecolor get secret --show-labels --watch --all-namespaces -o=wide"
abbr --add kgnsslwallowide "kubecolor get namespaces --show-labels --watch --all-namespaces -o=wide"
abbr --add kgwowideallsl "kubecolor get --watch -o=wide --all-namespaces --show-labels"
abbr --add kgpowowideallsl "kubecolor get pods --watch -o=wide --all-namespaces --show-labels"
abbr --add kgdepwowideallsl "kubecolor get deployment --watch -o=wide --all-namespaces --show-labels"
abbr --add kgstswowideallsl "kubecolor get statefulset --watch -o=wide --all-namespaces --show-labels"
abbr --add kgsvcwowideallsl "kubecolor get service --watch -o=wide --all-namespaces --show-labels"
abbr --add kgingwowideallsl "kubecolor get ingress --watch -o=wide --all-namespaces --show-labels"
abbr --add kgcmwowideallsl "kubecolor get configmap --watch -o=wide --all-namespaces --show-labels"
abbr --add kgsecwowideallsl "kubecolor get secret --watch -o=wide --all-namespaces --show-labels"
abbr --add kgnswowideallsl "kubecolor get namespaces --watch -o=wide --all-namespaces --show-labels"
abbr --add kgwowideslall "kubecolor get --watch -o=wide --show-labels --all-namespaces"
abbr --add kgpowowideslall "kubecolor get pods --watch -o=wide --show-labels --all-namespaces"
abbr --add kgdepwowideslall "kubecolor get deployment --watch -o=wide --show-labels --all-namespaces"
abbr --add kgstswowideslall "kubecolor get statefulset --watch -o=wide --show-labels --all-namespaces"
abbr --add kgsvcwowideslall "kubecolor get service --watch -o=wide --show-labels --all-namespaces"
abbr --add kgingwowideslall "kubecolor get ingress --watch -o=wide --show-labels --all-namespaces"
abbr --add kgcmwowideslall "kubecolor get configmap --watch -o=wide --show-labels --all-namespaces"
abbr --add kgsecwowideslall "kubecolor get secret --watch -o=wide --show-labels --all-namespaces"
abbr --add kgnswowideslall "kubecolor get namespaces --watch -o=wide --show-labels --all-namespaces"
abbr --add kgwallowidesl "kubecolor get --watch --all-namespaces -o=wide --show-labels"
abbr --add kgpowallowidesl "kubecolor get pods --watch --all-namespaces -o=wide --show-labels"
abbr --add kgdepwallowidesl "kubecolor get deployment --watch --all-namespaces -o=wide --show-labels"
abbr --add kgstswallowidesl "kubecolor get statefulset --watch --all-namespaces -o=wide --show-labels"
abbr --add kgsvcwallowidesl "kubecolor get service --watch --all-namespaces -o=wide --show-labels"
abbr --add kgingwallowidesl "kubecolor get ingress --watch --all-namespaces -o=wide --show-labels"
abbr --add kgcmwallowidesl "kubecolor get configmap --watch --all-namespaces -o=wide --show-labels"
abbr --add kgsecwallowidesl "kubecolor get secret --watch --all-namespaces -o=wide --show-labels"
abbr --add kgnswallowidesl "kubecolor get namespaces --watch --all-namespaces -o=wide --show-labels"
abbr --add kgwallslowide "kubecolor get --watch --all-namespaces --show-labels -o=wide"
abbr --add kgpowallslowide "kubecolor get pods --watch --all-namespaces --show-labels -o=wide"
abbr --add kgdepwallslowide "kubecolor get deployment --watch --all-namespaces --show-labels -o=wide"
abbr --add kgstswallslowide "kubecolor get statefulset --watch --all-namespaces --show-labels -o=wide"
abbr --add kgsvcwallslowide "kubecolor get service --watch --all-namespaces --show-labels -o=wide"
abbr --add kgingwallslowide "kubecolor get ingress --watch --all-namespaces --show-labels -o=wide"
abbr --add kgcmwallslowide "kubecolor get configmap --watch --all-namespaces --show-labels -o=wide"
abbr --add kgsecwallslowide "kubecolor get secret --watch --all-namespaces --show-labels -o=wide"
abbr --add kgnswallslowide "kubecolor get namespaces --watch --all-namespaces --show-labels -o=wide"
abbr --add kgwslowideall "kubecolor get --watch --show-labels -o=wide --all-namespaces"
abbr --add kgpowslowideall "kubecolor get pods --watch --show-labels -o=wide --all-namespaces"
abbr --add kgdepwslowideall "kubecolor get deployment --watch --show-labels -o=wide --all-namespaces"
abbr --add kgstswslowideall "kubecolor get statefulset --watch --show-labels -o=wide --all-namespaces"
abbr --add kgsvcwslowideall "kubecolor get service --watch --show-labels -o=wide --all-namespaces"
abbr --add kgingwslowideall "kubecolor get ingress --watch --show-labels -o=wide --all-namespaces"
abbr --add kgcmwslowideall "kubecolor get configmap --watch --show-labels -o=wide --all-namespaces"
abbr --add kgsecwslowideall "kubecolor get secret --watch --show-labels -o=wide --all-namespaces"
abbr --add kgnswslowideall "kubecolor get namespaces --watch --show-labels -o=wide --all-namespaces"
abbr --add kgwslallowide "kubecolor get --watch --show-labels --all-namespaces -o=wide"
abbr --add kgpowslallowide "kubecolor get pods --watch --show-labels --all-namespaces -o=wide"
abbr --add kgdepwslallowide "kubecolor get deployment --watch --show-labels --all-namespaces -o=wide"
abbr --add kgstswslallowide "kubecolor get statefulset --watch --show-labels --all-namespaces -o=wide"
abbr --add kgsvcwslallowide "kubecolor get service --watch --show-labels --all-namespaces -o=wide"
abbr --add kgingwslallowide "kubecolor get ingress --watch --show-labels --all-namespaces -o=wide"
abbr --add kgcmwslallowide "kubecolor get configmap --watch --show-labels --all-namespaces -o=wide"
abbr --add kgsecwslallowide "kubecolor get secret --watch --show-labels --all-namespaces -o=wide"
abbr --add kgnswslallowide "kubecolor get namespaces --watch --show-labels --all-namespaces -o=wide"
abbr --add kgf "kubecolor get --recursive -f"
abbr --add kdf "kubecolor describe --recursive -f"
abbr --add krmf "kubecolor delete --recursive -f"
abbr --add kgoyamlf "kubecolor get -o=yaml --recursive -f"
abbr --add kgowidef "kubecolor get -o=wide --recursive -f"
abbr --add kgojsonf "kubecolor get -o=json --recursive -f"
abbr --add kgslf "kubecolor get --show-labels --recursive -f"
abbr --add kgwf "kubecolor get --watch --recursive -f"
abbr --add kgwoyamlf "kubecolor get --watch -o=yaml --recursive -f"
abbr --add kgowideslf "kubecolor get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubecolor get --show-labels -o=wide --recursive -f"
abbr --add kgwowidef "kubecolor get --watch -o=wide --recursive -f"
abbr --add kgwojsonf "kubecolor get --watch -o=json --recursive -f"
abbr --add kgslwf "kubecolor get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubecolor get --watch --show-labels --recursive -f"
abbr --add kgslwowidef "kubecolor get --show-labels --watch -o=wide --recursive -f"
abbr --add kgwowideslf "kubecolor get --watch -o=wide --show-labels --recursive -f"
abbr --add kgwslowidef "kubecolor get --watch --show-labels -o=wide --recursive -f"
abbr --add kgl "kubecolor get -l"
abbr --add ksysgl "kubecolor --namespace=kube-system get -l"
abbr --add kdl "kubecolor describe -l"
abbr --add ksysdl "kubecolor --namespace=kube-system describe -l"
abbr --add krml "kubecolor delete -l"
abbr --add ksysrml "kubecolor --namespace=kube-system delete -l"
abbr --add kgpol "kubecolor get pods -l"
abbr --add ksysgpol "kubecolor --namespace=kube-system get pods -l"
abbr --add kdpol "kubecolor describe pods -l"
abbr --add ksysdpol "kubecolor --namespace=kube-system describe pods -l"
abbr --add krmpol "kubecolor delete pods -l"
abbr --add ksysrmpol "kubecolor --namespace=kube-system delete pods -l"
abbr --add kgdepl "kubecolor get deployment -l"
abbr --add ksysgdepl "kubecolor --namespace=kube-system get deployment -l"
abbr --add kddepl "kubecolor describe deployment -l"
abbr --add ksysddepl "kubecolor --namespace=kube-system describe deployment -l"
abbr --add krmdepl "kubecolor delete deployment -l"
abbr --add ksysrmdepl "kubecolor --namespace=kube-system delete deployment -l"
abbr --add kgstsl "kubecolor get statefulset -l"
abbr --add ksysgstsl "kubecolor --namespace=kube-system get statefulset -l"
abbr --add kdstsl "kubecolor describe statefulset -l"
abbr --add ksysdstsl "kubecolor --namespace=kube-system describe statefulset -l"
abbr --add krmstsl "kubecolor delete statefulset -l"
abbr --add ksysrmstsl "kubecolor --namespace=kube-system delete statefulset -l"
abbr --add kgsvcl "kubecolor get service -l"
abbr --add ksysgsvcl "kubecolor --namespace=kube-system get service -l"
abbr --add kdsvcl "kubecolor describe service -l"
abbr --add ksysdsvcl "kubecolor --namespace=kube-system describe service -l"
abbr --add krmsvcl "kubecolor delete service -l"
abbr --add ksysrmsvcl "kubecolor --namespace=kube-system delete service -l"
abbr --add kgingl "kubecolor get ingress -l"
abbr --add ksysgingl "kubecolor --namespace=kube-system get ingress -l"
abbr --add kdingl "kubecolor describe ingress -l"
abbr --add ksysdingl "kubecolor --namespace=kube-system describe ingress -l"
abbr --add krmingl "kubecolor delete ingress -l"
abbr --add ksysrmingl "kubecolor --namespace=kube-system delete ingress -l"
abbr --add kgcml "kubecolor get configmap -l"
abbr --add ksysgcml "kubecolor --namespace=kube-system get configmap -l"
abbr --add kdcml "kubecolor describe configmap -l"
abbr --add ksysdcml "kubecolor --namespace=kube-system describe configmap -l"
abbr --add krmcml "kubecolor delete configmap -l"
abbr --add ksysrmcml "kubecolor --namespace=kube-system delete configmap -l"
abbr --add kgsecl "kubecolor get secret -l"
abbr --add ksysgsecl "kubecolor --namespace=kube-system get secret -l"
abbr --add kdsecl "kubecolor describe secret -l"
abbr --add ksysdsecl "kubecolor --namespace=kube-system describe secret -l"
abbr --add krmsecl "kubecolor delete secret -l"
abbr --add ksysrmsecl "kubecolor --namespace=kube-system delete secret -l"
abbr --add kgnol "kubecolor get nodes -l"
abbr --add kdnol "kubecolor describe nodes -l"
abbr --add kgnsl "kubecolor get namespaces -l"
abbr --add kdnsl "kubecolor describe namespaces -l"
abbr --add krmnsl "kubecolor delete namespaces -l"
abbr --add kgoyamll "kubecolor get -o=yaml -l"
abbr --add ksysgoyamll "kubecolor --namespace=kube-system get -o=yaml -l"
abbr --add kgpooyamll "kubecolor get pods -o=yaml -l"
abbr --add ksysgpooyamll "kubecolor --namespace=kube-system get pods -o=yaml -l"
abbr --add kgdepoyamll "kubecolor get deployment -o=yaml -l"
abbr --add ksysgdepoyamll "kubecolor --namespace=kube-system get deployment -o=yaml -l"
abbr --add kgstsoyamll "kubecolor get statefulset -o=yaml -l"
abbr --add ksysgstsoyamll "kubecolor --namespace=kube-system get statefulset -o=yaml -l"
abbr --add kgsvcoyamll "kubecolor get service -o=yaml -l"
abbr --add ksysgsvcoyamll "kubecolor --namespace=kube-system get service -o=yaml -l"
abbr --add kgingoyamll "kubecolor get ingress -o=yaml -l"
abbr --add ksysgingoyamll "kubecolor --namespace=kube-system get ingress -o=yaml -l"
abbr --add kgcmoyamll "kubecolor get configmap -o=yaml -l"
abbr --add ksysgcmoyamll "kubecolor --namespace=kube-system get configmap -o=yaml -l"
abbr --add kgsecoyamll "kubecolor get secret -o=yaml -l"
abbr --add ksysgsecoyamll "kubecolor --namespace=kube-system get secret -o=yaml -l"
abbr --add kgnooyamll "kubecolor get nodes -o=yaml -l"
abbr --add kgnsoyamll "kubecolor get namespaces -o=yaml -l"
abbr --add kgowidel "kubecolor get -o=wide -l"
abbr --add ksysgowidel "kubecolor --namespace=kube-system get -o=wide -l"
abbr --add kgpoowidel "kubecolor get pods -o=wide -l"
abbr --add ksysgpoowidel "kubecolor --namespace=kube-system get pods -o=wide -l"
abbr --add kgdepowidel "kubecolor get deployment -o=wide -l"
abbr --add ksysgdepowidel "kubecolor --namespace=kube-system get deployment -o=wide -l"
abbr --add kgstsowidel "kubecolor get statefulset -o=wide -l"
abbr --add ksysgstsowidel "kubecolor --namespace=kube-system get statefulset -o=wide -l"
abbr --add kgsvcowidel "kubecolor get service -o=wide -l"
abbr --add ksysgsvcowidel "kubecolor --namespace=kube-system get service -o=wide -l"
abbr --add kgingowidel "kubecolor get ingress -o=wide -l"
abbr --add ksysgingowidel "kubecolor --namespace=kube-system get ingress -o=wide -l"
abbr --add kgcmowidel "kubecolor get configmap -o=wide -l"
abbr --add ksysgcmowidel "kubecolor --namespace=kube-system get configmap -o=wide -l"
abbr --add kgsecowidel "kubecolor get secret -o=wide -l"
abbr --add ksysgsecowidel "kubecolor --namespace=kube-system get secret -o=wide -l"
abbr --add kgnoowidel "kubecolor get nodes -o=wide -l"
abbr --add kgnsowidel "kubecolor get namespaces -o=wide -l"
abbr --add kgojsonl "kubecolor get -o=json -l"
abbr --add ksysgojsonl "kubecolor --namespace=kube-system get -o=json -l"
abbr --add kgpoojsonl "kubecolor get pods -o=json -l"
abbr --add ksysgpoojsonl "kubecolor --namespace=kube-system get pods -o=json -l"
abbr --add kgdepojsonl "kubecolor get deployment -o=json -l"
abbr --add ksysgdepojsonl "kubecolor --namespace=kube-system get deployment -o=json -l"
abbr --add kgstsojsonl "kubecolor get statefulset -o=json -l"
abbr --add ksysgstsojsonl "kubecolor --namespace=kube-system get statefulset -o=json -l"
abbr --add kgsvcojsonl "kubecolor get service -o=json -l"
abbr --add ksysgsvcojsonl "kubecolor --namespace=kube-system get service -o=json -l"
abbr --add kgingojsonl "kubecolor get ingress -o=json -l"
abbr --add ksysgingojsonl "kubecolor --namespace=kube-system get ingress -o=json -l"
abbr --add kgcmojsonl "kubecolor get configmap -o=json -l"
abbr --add ksysgcmojsonl "kubecolor --namespace=kube-system get configmap -o=json -l"
abbr --add kgsecojsonl "kubecolor get secret -o=json -l"
abbr --add ksysgsecojsonl "kubecolor --namespace=kube-system get secret -o=json -l"
abbr --add kgnoojsonl "kubecolor get nodes -o=json -l"
abbr --add kgnsojsonl "kubecolor get namespaces -o=json -l"
abbr --add kgsll "kubecolor get --show-labels -l"
abbr --add ksysgsll "kubecolor --namespace=kube-system get --show-labels -l"
abbr --add kgposll "kubecolor get pods --show-labels -l"
abbr --add ksysgposll "kubecolor --namespace=kube-system get pods --show-labels -l"
abbr --add kgdepsll "kubecolor get deployment --show-labels -l"
abbr --add ksysgdepsll "kubecolor --namespace=kube-system get deployment --show-labels -l"
abbr --add kgstssll "kubecolor get statefulset --show-labels -l"
abbr --add ksysgstssll "kubecolor --namespace=kube-system get statefulset --show-labels -l"
abbr --add kgsvcsll "kubecolor get service --show-labels -l"
abbr --add ksysgsvcsll "kubecolor --namespace=kube-system get service --show-labels -l"
abbr --add kgingsll "kubecolor get ingress --show-labels -l"
abbr --add ksysgingsll "kubecolor --namespace=kube-system get ingress --show-labels -l"
abbr --add kgcmsll "kubecolor get configmap --show-labels -l"
abbr --add ksysgcmsll "kubecolor --namespace=kube-system get configmap --show-labels -l"
abbr --add kgsecsll "kubecolor get secret --show-labels -l"
abbr --add ksysgsecsll "kubecolor --namespace=kube-system get secret --show-labels -l"
abbr --add kgnosll "kubecolor get nodes --show-labels -l"
abbr --add kgnssll "kubecolor get namespaces --show-labels -l"
abbr --add kgwl "kubecolor get --watch -l"
abbr --add ksysgwl "kubecolor --namespace=kube-system get --watch -l"
abbr --add kgpowl "kubecolor get pods --watch -l"
abbr --add ksysgpowl "kubecolor --namespace=kube-system get pods --watch -l"
abbr --add kgdepwl "kubecolor get deployment --watch -l"
abbr --add ksysgdepwl "kubecolor --namespace=kube-system get deployment --watch -l"
abbr --add kgstswl "kubecolor get statefulset --watch -l"
abbr --add ksysgstswl "kubecolor --namespace=kube-system get statefulset --watch -l"
abbr --add kgsvcwl "kubecolor get service --watch -l"
abbr --add ksysgsvcwl "kubecolor --namespace=kube-system get service --watch -l"
abbr --add kgingwl "kubecolor get ingress --watch -l"
abbr --add ksysgingwl "kubecolor --namespace=kube-system get ingress --watch -l"
abbr --add kgcmwl "kubecolor get configmap --watch -l"
abbr --add ksysgcmwl "kubecolor --namespace=kube-system get configmap --watch -l"
abbr --add kgsecwl "kubecolor get secret --watch -l"
abbr --add ksysgsecwl "kubecolor --namespace=kube-system get secret --watch -l"
abbr --add kgnowl "kubecolor get nodes --watch -l"
abbr --add kgnswl "kubecolor get namespaces --watch -l"
abbr --add kgwoyamll "kubecolor get --watch -o=yaml -l"
abbr --add ksysgwoyamll "kubecolor --namespace=kube-system get --watch -o=yaml -l"
abbr --add kgpowoyamll "kubecolor get pods --watch -o=yaml -l"
abbr --add ksysgpowoyamll "kubecolor --namespace=kube-system get pods --watch -o=yaml -l"
abbr --add kgdepwoyamll "kubecolor get deployment --watch -o=yaml -l"
abbr --add ksysgdepwoyamll "kubecolor --namespace=kube-system get deployment --watch -o=yaml -l"
abbr --add kgstswoyamll "kubecolor get statefulset --watch -o=yaml -l"
abbr --add ksysgstswoyamll "kubecolor --namespace=kube-system get statefulset --watch -o=yaml -l"
abbr --add kgsvcwoyamll "kubecolor get service --watch -o=yaml -l"
abbr --add ksysgsvcwoyamll "kubecolor --namespace=kube-system get service --watch -o=yaml -l"
abbr --add kgingwoyamll "kubecolor get ingress --watch -o=yaml -l"
abbr --add ksysgingwoyamll "kubecolor --namespace=kube-system get ingress --watch -o=yaml -l"
abbr --add kgcmwoyamll "kubecolor get configmap --watch -o=yaml -l"
abbr --add ksysgcmwoyamll "kubecolor --namespace=kube-system get configmap --watch -o=yaml -l"
abbr --add kgsecwoyamll "kubecolor get secret --watch -o=yaml -l"
abbr --add ksysgsecwoyamll "kubecolor --namespace=kube-system get secret --watch -o=yaml -l"
abbr --add kgnowoyamll "kubecolor get nodes --watch -o=yaml -l"
abbr --add kgnswoyamll "kubecolor get namespaces --watch -o=yaml -l"
abbr --add kgowidesll "kubecolor get -o=wide --show-labels -l"
abbr --add ksysgowidesll "kubecolor --namespace=kube-system get -o=wide --show-labels -l"
abbr --add kgpoowidesll "kubecolor get pods -o=wide --show-labels -l"
abbr --add ksysgpoowidesll "kubecolor --namespace=kube-system get pods -o=wide --show-labels -l"
abbr --add kgdepowidesll "kubecolor get deployment -o=wide --show-labels -l"
abbr --add ksysgdepowidesll "kubecolor --namespace=kube-system get deployment -o=wide --show-labels -l"
abbr --add kgstsowidesll "kubecolor get statefulset -o=wide --show-labels -l"
abbr --add ksysgstsowidesll "kubecolor --namespace=kube-system get statefulset -o=wide --show-labels -l"
abbr --add kgsvcowidesll "kubecolor get service -o=wide --show-labels -l"
abbr --add ksysgsvcowidesll "kubecolor --namespace=kube-system get service -o=wide --show-labels -l"
abbr --add kgingowidesll "kubecolor get ingress -o=wide --show-labels -l"
abbr --add ksysgingowidesll "kubecolor --namespace=kube-system get ingress -o=wide --show-labels -l"
abbr --add kgcmowidesll "kubecolor get configmap -o=wide --show-labels -l"
abbr --add ksysgcmowidesll "kubecolor --namespace=kube-system get configmap -o=wide --show-labels -l"
abbr --add kgsecowidesll "kubecolor get secret -o=wide --show-labels -l"
abbr --add ksysgsecowidesll "kubecolor --namespace=kube-system get secret -o=wide --show-labels -l"
abbr --add kgnoowidesll "kubecolor get nodes -o=wide --show-labels -l"
abbr --add kgnsowidesll "kubecolor get namespaces -o=wide --show-labels -l"
abbr --add kgslowidel "kubecolor get --show-labels -o=wide -l"
abbr --add ksysgslowidel "kubecolor --namespace=kube-system get --show-labels -o=wide -l"
abbr --add kgposlowidel "kubecolor get pods --show-labels -o=wide -l"
abbr --add ksysgposlowidel "kubecolor --namespace=kube-system get pods --show-labels -o=wide -l"
abbr --add kgdepslowidel "kubecolor get deployment --show-labels -o=wide -l"
abbr --add ksysgdepslowidel "kubecolor --namespace=kube-system get deployment --show-labels -o=wide -l"
abbr --add kgstsslowidel "kubecolor get statefulset --show-labels -o=wide -l"
abbr --add ksysgstsslowidel "kubecolor --namespace=kube-system get statefulset --show-labels -o=wide -l"
abbr --add kgsvcslowidel "kubecolor get service --show-labels -o=wide -l"
abbr --add ksysgsvcslowidel "kubecolor --namespace=kube-system get service --show-labels -o=wide -l"
abbr --add kgingslowidel "kubecolor get ingress --show-labels -o=wide -l"
abbr --add ksysgingslowidel "kubecolor --namespace=kube-system get ingress --show-labels -o=wide -l"
abbr --add kgcmslowidel "kubecolor get configmap --show-labels -o=wide -l"
abbr --add ksysgcmslowidel "kubecolor --namespace=kube-system get configmap --show-labels -o=wide -l"
abbr --add kgsecslowidel "kubecolor get secret --show-labels -o=wide -l"
abbr --add ksysgsecslowidel "kubecolor --namespace=kube-system get secret --show-labels -o=wide -l"
abbr --add kgnoslowidel "kubecolor get nodes --show-labels -o=wide -l"
abbr --add kgnsslowidel "kubecolor get namespaces --show-labels -o=wide -l"
abbr --add kgwowidel "kubecolor get --watch -o=wide -l"
abbr --add ksysgwowidel "kubecolor --namespace=kube-system get --watch -o=wide -l"
abbr --add kgpowowidel "kubecolor get pods --watch -o=wide -l"
abbr --add ksysgpowowidel "kubecolor --namespace=kube-system get pods --watch -o=wide -l"
abbr --add kgdepwowidel "kubecolor get deployment --watch -o=wide -l"
abbr --add ksysgdepwowidel "kubecolor --namespace=kube-system get deployment --watch -o=wide -l"
abbr --add kgstswowidel "kubecolor get statefulset --watch -o=wide -l"
abbr --add ksysgstswowidel "kubecolor --namespace=kube-system get statefulset --watch -o=wide -l"
abbr --add kgsvcwowidel "kubecolor get service --watch -o=wide -l"
abbr --add ksysgsvcwowidel "kubecolor --namespace=kube-system get service --watch -o=wide -l"
abbr --add kgingwowidel "kubecolor get ingress --watch -o=wide -l"
abbr --add ksysgingwowidel "kubecolor --namespace=kube-system get ingress --watch -o=wide -l"
abbr --add kgcmwowidel "kubecolor get configmap --watch -o=wide -l"
abbr --add ksysgcmwowidel "kubecolor --namespace=kube-system get configmap --watch -o=wide -l"
abbr --add kgsecwowidel "kubecolor get secret --watch -o=wide -l"
abbr --add ksysgsecwowidel "kubecolor --namespace=kube-system get secret --watch -o=wide -l"
abbr --add kgnowowidel "kubecolor get nodes --watch -o=wide -l"
abbr --add kgnswowidel "kubecolor get namespaces --watch -o=wide -l"
abbr --add kgwojsonl "kubecolor get --watch -o=json -l"
abbr --add ksysgwojsonl "kubecolor --namespace=kube-system get --watch -o=json -l"
abbr --add kgpowojsonl "kubecolor get pods --watch -o=json -l"
abbr --add ksysgpowojsonl "kubecolor --namespace=kube-system get pods --watch -o=json -l"
abbr --add kgdepwojsonl "kubecolor get deployment --watch -o=json -l"
abbr --add ksysgdepwojsonl "kubecolor --namespace=kube-system get deployment --watch -o=json -l"
abbr --add kgstswojsonl "kubecolor get statefulset --watch -o=json -l"
abbr --add ksysgstswojsonl "kubecolor --namespace=kube-system get statefulset --watch -o=json -l"
abbr --add kgsvcwojsonl "kubecolor get service --watch -o=json -l"
abbr --add ksysgsvcwojsonl "kubecolor --namespace=kube-system get service --watch -o=json -l"
abbr --add kgingwojsonl "kubecolor get ingress --watch -o=json -l"
abbr --add ksysgingwojsonl "kubecolor --namespace=kube-system get ingress --watch -o=json -l"
abbr --add kgcmwojsonl "kubecolor get configmap --watch -o=json -l"
abbr --add ksysgcmwojsonl "kubecolor --namespace=kube-system get configmap --watch -o=json -l"
abbr --add kgsecwojsonl "kubecolor get secret --watch -o=json -l"
abbr --add ksysgsecwojsonl "kubecolor --namespace=kube-system get secret --watch -o=json -l"
abbr --add kgnowojsonl "kubecolor get nodes --watch -o=json -l"
abbr --add kgnswojsonl "kubecolor get namespaces --watch -o=json -l"
abbr --add kgslwl "kubecolor get --show-labels --watch -l"
abbr --add ksysgslwl "kubecolor --namespace=kube-system get --show-labels --watch -l"
abbr --add kgposlwl "kubecolor get pods --show-labels --watch -l"
abbr --add ksysgposlwl "kubecolor --namespace=kube-system get pods --show-labels --watch -l"
abbr --add kgdepslwl "kubecolor get deployment --show-labels --watch -l"
abbr --add ksysgdepslwl "kubecolor --namespace=kube-system get deployment --show-labels --watch -l"
abbr --add kgstsslwl "kubecolor get statefulset --show-labels --watch -l"
abbr --add ksysgstsslwl "kubecolor --namespace=kube-system get statefulset --show-labels --watch -l"
abbr --add kgsvcslwl "kubecolor get service --show-labels --watch -l"
abbr --add ksysgsvcslwl "kubecolor --namespace=kube-system get service --show-labels --watch -l"
abbr --add kgingslwl "kubecolor get ingress --show-labels --watch -l"
abbr --add ksysgingslwl "kubecolor --namespace=kube-system get ingress --show-labels --watch -l"
abbr --add kgcmslwl "kubecolor get configmap --show-labels --watch -l"
abbr --add ksysgcmslwl "kubecolor --namespace=kube-system get configmap --show-labels --watch -l"
abbr --add kgsecslwl "kubecolor get secret --show-labels --watch -l"
abbr --add ksysgsecslwl "kubecolor --namespace=kube-system get secret --show-labels --watch -l"
abbr --add kgnoslwl "kubecolor get nodes --show-labels --watch -l"
abbr --add kgnsslwl "kubecolor get namespaces --show-labels --watch -l"
abbr --add kgwsll "kubecolor get --watch --show-labels -l"
abbr --add ksysgwsll "kubecolor --namespace=kube-system get --watch --show-labels -l"
abbr --add kgpowsll "kubecolor get pods --watch --show-labels -l"
abbr --add ksysgpowsll "kubecolor --namespace=kube-system get pods --watch --show-labels -l"
abbr --add kgdepwsll "kubecolor get deployment --watch --show-labels -l"
abbr --add ksysgdepwsll "kubecolor --namespace=kube-system get deployment --watch --show-labels -l"
abbr --add kgstswsll "kubecolor get statefulset --watch --show-labels -l"
abbr --add ksysgstswsll "kubecolor --namespace=kube-system get statefulset --watch --show-labels -l"
abbr --add kgsvcwsll "kubecolor get service --watch --show-labels -l"
abbr --add ksysgsvcwsll "kubecolor --namespace=kube-system get service --watch --show-labels -l"
abbr --add kgingwsll "kubecolor get ingress --watch --show-labels -l"
abbr --add ksysgingwsll "kubecolor --namespace=kube-system get ingress --watch --show-labels -l"
abbr --add kgcmwsll "kubecolor get configmap --watch --show-labels -l"
abbr --add ksysgcmwsll "kubecolor --namespace=kube-system get configmap --watch --show-labels -l"
abbr --add kgsecwsll "kubecolor get secret --watch --show-labels -l"
abbr --add ksysgsecwsll "kubecolor --namespace=kube-system get secret --watch --show-labels -l"
abbr --add kgnowsll "kubecolor get nodes --watch --show-labels -l"
abbr --add kgnswsll "kubecolor get namespaces --watch --show-labels -l"
abbr --add kgslwowidel "kubecolor get --show-labels --watch -o=wide -l"
abbr --add ksysgslwowidel "kubecolor --namespace=kube-system get --show-labels --watch -o=wide -l"
abbr --add kgposlwowidel "kubecolor get pods --show-labels --watch -o=wide -l"
abbr --add ksysgposlwowidel "kubecolor --namespace=kube-system get pods --show-labels --watch -o=wide -l"
abbr --add kgdepslwowidel "kubecolor get deployment --show-labels --watch -o=wide -l"
abbr --add ksysgdepslwowidel "kubecolor --namespace=kube-system get deployment --show-labels --watch -o=wide -l"
abbr --add kgstsslwowidel "kubecolor get statefulset --show-labels --watch -o=wide -l"
abbr --add ksysgstsslwowidel "kubecolor --namespace=kube-system get statefulset --show-labels --watch -o=wide -l"
abbr --add kgsvcslwowidel "kubecolor get service --show-labels --watch -o=wide -l"
abbr --add ksysgsvcslwowidel "kubecolor --namespace=kube-system get service --show-labels --watch -o=wide -l"
abbr --add kgingslwowidel "kubecolor get ingress --show-labels --watch -o=wide -l"
abbr --add ksysgingslwowidel "kubecolor --namespace=kube-system get ingress --show-labels --watch -o=wide -l"
abbr --add kgcmslwowidel "kubecolor get configmap --show-labels --watch -o=wide -l"
abbr --add ksysgcmslwowidel "kubecolor --namespace=kube-system get configmap --show-labels --watch -o=wide -l"
abbr --add kgsecslwowidel "kubecolor get secret --show-labels --watch -o=wide -l"
abbr --add ksysgsecslwowidel "kubecolor --namespace=kube-system get secret --show-labels --watch -o=wide -l"
abbr --add kgnoslwowidel "kubecolor get nodes --show-labels --watch -o=wide -l"
abbr --add kgnsslwowidel "kubecolor get namespaces --show-labels --watch -o=wide -l"
abbr --add kgwowidesll "kubecolor get --watch -o=wide --show-labels -l"
abbr --add ksysgwowidesll "kubecolor --namespace=kube-system get --watch -o=wide --show-labels -l"
abbr --add kgpowowidesll "kubecolor get pods --watch -o=wide --show-labels -l"
abbr --add ksysgpowowidesll "kubecolor --namespace=kube-system get pods --watch -o=wide --show-labels -l"
abbr --add kgdepwowidesll "kubecolor get deployment --watch -o=wide --show-labels -l"
abbr --add ksysgdepwowidesll "kubecolor --namespace=kube-system get deployment --watch -o=wide --show-labels -l"
abbr --add kgstswowidesll "kubecolor get statefulset --watch -o=wide --show-labels -l"
abbr --add ksysgstswowidesll "kubecolor --namespace=kube-system get statefulset --watch -o=wide --show-labels -l"
abbr --add kgsvcwowidesll "kubecolor get service --watch -o=wide --show-labels -l"
abbr --add ksysgsvcwowidesll "kubecolor --namespace=kube-system get service --watch -o=wide --show-labels -l"
abbr --add kgingwowidesll "kubecolor get ingress --watch -o=wide --show-labels -l"
abbr --add ksysgingwowidesll "kubecolor --namespace=kube-system get ingress --watch -o=wide --show-labels -l"
abbr --add kgcmwowidesll "kubecolor get configmap --watch -o=wide --show-labels -l"
abbr --add ksysgcmwowidesll "kubecolor --namespace=kube-system get configmap --watch -o=wide --show-labels -l"
abbr --add kgsecwowidesll "kubecolor get secret --watch -o=wide --show-labels -l"
abbr --add ksysgsecwowidesll "kubecolor --namespace=kube-system get secret --watch -o=wide --show-labels -l"
abbr --add kgnowowidesll "kubecolor get nodes --watch -o=wide --show-labels -l"
abbr --add kgnswowidesll "kubecolor get namespaces --watch -o=wide --show-labels -l"
abbr --add kgwslowidel "kubecolor get --watch --show-labels -o=wide -l"
abbr --add ksysgwslowidel "kubecolor --namespace=kube-system get --watch --show-labels -o=wide -l"
abbr --add kgpowslowidel "kubecolor get pods --watch --show-labels -o=wide -l"
abbr --add ksysgpowslowidel "kubecolor --namespace=kube-system get pods --watch --show-labels -o=wide -l"
abbr --add kgdepwslowidel "kubecolor get deployment --watch --show-labels -o=wide -l"
abbr --add ksysgdepwslowidel "kubecolor --namespace=kube-system get deployment --watch --show-labels -o=wide -l"
abbr --add kgstswslowidel "kubecolor get statefulset --watch --show-labels -o=wide -l"
abbr --add ksysgstswslowidel "kubecolor --namespace=kube-system get statefulset --watch --show-labels -o=wide -l"
abbr --add kgsvcwslowidel "kubecolor get service --watch --show-labels -o=wide -l"
abbr --add ksysgsvcwslowidel "kubecolor --namespace=kube-system get service --watch --show-labels -o=wide -l"
abbr --add kgingwslowidel "kubecolor get ingress --watch --show-labels -o=wide -l"
abbr --add ksysgingwslowidel "kubecolor --namespace=kube-system get ingress --watch --show-labels -o=wide -l"
abbr --add kgcmwslowidel "kubecolor get configmap --watch --show-labels -o=wide -l"
abbr --add ksysgcmwslowidel "kubecolor --namespace=kube-system get configmap --watch --show-labels -o=wide -l"
abbr --add kgsecwslowidel "kubecolor get secret --watch --show-labels -o=wide -l"
abbr --add ksysgsecwslowidel "kubecolor --namespace=kube-system get secret --watch --show-labels -o=wide -l"
abbr --add kgnowslowidel "kubecolor get nodes --watch --show-labels -o=wide -l"
abbr --add kgnswslowidel "kubecolor get namespaces --watch --show-labels -o=wide -l"
abbr --add kexn "kubecolor exec -i -t --namespace"
abbr --add klon "kubecolor logs -f --namespace"
abbr --add kpfn "kubecolor port-forward --namespace"
abbr --add kgn "kubecolor get --namespace"
abbr --add kdn "kubecolor describe --namespace"
abbr --add krmn "kubecolor delete --namespace"
abbr --add kgpon "kubecolor get pods --namespace"
abbr --add kdpon "kubecolor describe pods --namespace"
abbr --add krmpon "kubecolor delete pods --namespace"
abbr --add kgdepn "kubecolor get deployment --namespace"
abbr --add kddepn "kubecolor describe deployment --namespace"
abbr --add krmdepn "kubecolor delete deployment --namespace"
abbr --add kgstsn "kubecolor get statefulset --namespace"
abbr --add kdstsn "kubecolor describe statefulset --namespace"
abbr --add krmstsn "kubecolor delete statefulset --namespace"
abbr --add kgsvcn "kubecolor get service --namespace"
abbr --add kdsvcn "kubecolor describe service --namespace"
abbr --add krmsvcn "kubecolor delete service --namespace"
abbr --add kgingn "kubecolor get ingress --namespace"
abbr --add kdingn "kubecolor describe ingress --namespace"
abbr --add krmingn "kubecolor delete ingress --namespace"
abbr --add kgcmn "kubecolor get configmap --namespace"
abbr --add kdcmn "kubecolor describe configmap --namespace"
abbr --add krmcmn "kubecolor delete configmap --namespace"
abbr --add kgsecn "kubecolor get secret --namespace"
abbr --add kdsecn "kubecolor describe secret --namespace"
abbr --add krmsecn "kubecolor delete secret --namespace"
abbr --add kgoyamln "kubecolor get -o=yaml --namespace"
abbr --add kgpooyamln "kubecolor get pods -o=yaml --namespace"
abbr --add kgdepoyamln "kubecolor get deployment -o=yaml --namespace"
abbr --add kgstsoyamln "kubecolor get statefulset -o=yaml --namespace"
abbr --add kgsvcoyamln "kubecolor get service -o=yaml --namespace"
abbr --add kgingoyamln "kubecolor get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "kubecolor get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "kubecolor get secret -o=yaml --namespace"
abbr --add kgowiden "kubecolor get -o=wide --namespace"
abbr --add kgpoowiden "kubecolor get pods -o=wide --namespace"
abbr --add kgdepowiden "kubecolor get deployment -o=wide --namespace"
abbr --add kgstsowiden "kubecolor get statefulset -o=wide --namespace"
abbr --add kgsvcowiden "kubecolor get service -o=wide --namespace"
abbr --add kgingowiden "kubecolor get ingress -o=wide --namespace"
abbr --add kgcmowiden "kubecolor get configmap -o=wide --namespace"
abbr --add kgsecowiden "kubecolor get secret -o=wide --namespace"
abbr --add kgojsonn "kubecolor get -o=json --namespace"
abbr --add kgpoojsonn "kubecolor get pods -o=json --namespace"
abbr --add kgdepojsonn "kubecolor get deployment -o=json --namespace"
abbr --add kgstsojsonn "kubecolor get statefulset -o=json --namespace"
abbr --add kgsvcojsonn "kubecolor get service -o=json --namespace"
abbr --add kgingojsonn "kubecolor get ingress -o=json --namespace"
abbr --add kgcmojsonn "kubecolor get configmap -o=json --namespace"
abbr --add kgsecojsonn "kubecolor get secret -o=json --namespace"
abbr --add kgsln "kubecolor get --show-labels --namespace"
abbr --add kgposln "kubecolor get pods --show-labels --namespace"
abbr --add kgdepsln "kubecolor get deployment --show-labels --namespace"
abbr --add kgstssln "kubecolor get statefulset --show-labels --namespace"
abbr --add kgsvcsln "kubecolor get service --show-labels --namespace"
abbr --add kgingsln "kubecolor get ingress --show-labels --namespace"
abbr --add kgcmsln "kubecolor get configmap --show-labels --namespace"
abbr --add kgsecsln "kubecolor get secret --show-labels --namespace"
abbr --add kgwn "kubecolor get --watch --namespace"
abbr --add kgpown "kubecolor get pods --watch --namespace"
abbr --add kgdepwn "kubecolor get deployment --watch --namespace"
abbr --add kgstswn "kubecolor get statefulset --watch --namespace"
abbr --add kgsvcwn "kubecolor get service --watch --namespace"
abbr --add kgingwn "kubecolor get ingress --watch --namespace"
abbr --add kgcmwn "kubecolor get configmap --watch --namespace"
abbr --add kgsecwn "kubecolor get secret --watch --namespace"
abbr --add kgwoyamln "kubecolor get --watch -o=yaml --namespace"
abbr --add kgpowoyamln "kubecolor get pods --watch -o=yaml --namespace"
abbr --add kgdepwoyamln "kubecolor get deployment --watch -o=yaml --namespace"
abbr --add kgstswoyamln "kubecolor get statefulset --watch -o=yaml --namespace"
abbr --add kgsvcwoyamln "kubecolor get service --watch -o=yaml --namespace"
abbr --add kgingwoyamln "kubecolor get ingress --watch -o=yaml --namespace"
abbr --add kgcmwoyamln "kubecolor get configmap --watch -o=yaml --namespace"
abbr --add kgsecwoyamln "kubecolor get secret --watch -o=yaml --namespace"
abbr --add kgowidesln "kubecolor get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "kubecolor get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "kubecolor get deployment -o=wide --show-labels --namespace"
abbr --add kgstsowidesln "kubecolor get statefulset -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "kubecolor get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "kubecolor get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "kubecolor get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "kubecolor get secret -o=wide --show-labels --namespace"
abbr --add kgslowiden "kubecolor get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "kubecolor get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "kubecolor get deployment --show-labels -o=wide --namespace"
abbr --add kgstsslowiden "kubecolor get statefulset --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "kubecolor get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "kubecolor get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "kubecolor get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "kubecolor get secret --show-labels -o=wide --namespace"
abbr --add kgwowiden "kubecolor get --watch -o=wide --namespace"
abbr --add kgpowowiden "kubecolor get pods --watch -o=wide --namespace"
abbr --add kgdepwowiden "kubecolor get deployment --watch -o=wide --namespace"
abbr --add kgstswowiden "kubecolor get statefulset --watch -o=wide --namespace"
abbr --add kgsvcwowiden "kubecolor get service --watch -o=wide --namespace"
abbr --add kgingwowiden "kubecolor get ingress --watch -o=wide --namespace"
abbr --add kgcmwowiden "kubecolor get configmap --watch -o=wide --namespace"
abbr --add kgsecwowiden "kubecolor get secret --watch -o=wide --namespace"
abbr --add kgwojsonn "kubecolor get --watch -o=json --namespace"
abbr --add kgpowojsonn "kubecolor get pods --watch -o=json --namespace"
abbr --add kgdepwojsonn "kubecolor get deployment --watch -o=json --namespace"
abbr --add kgstswojsonn "kubecolor get statefulset --watch -o=json --namespace"
abbr --add kgsvcwojsonn "kubecolor get service --watch -o=json --namespace"
abbr --add kgingwojsonn "kubecolor get ingress --watch -o=json --namespace"
abbr --add kgcmwojsonn "kubecolor get configmap --watch -o=json --namespace"
abbr --add kgsecwojsonn "kubecolor get secret --watch -o=json --namespace"
abbr --add kgslwn "kubecolor get --show-labels --watch --namespace"
abbr --add kgposlwn "kubecolor get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "kubecolor get deployment --show-labels --watch --namespace"
abbr --add kgstsslwn "kubecolor get statefulset --show-labels --watch --namespace"
abbr --add kgsvcslwn "kubecolor get service --show-labels --watch --namespace"
abbr --add kgingslwn "kubecolor get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "kubecolor get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "kubecolor get secret --show-labels --watch --namespace"
abbr --add kgwsln "kubecolor get --watch --show-labels --namespace"
abbr --add kgpowsln "kubecolor get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "kubecolor get deployment --watch --show-labels --namespace"
abbr --add kgstswsln "kubecolor get statefulset --watch --show-labels --namespace"
abbr --add kgsvcwsln "kubecolor get service --watch --show-labels --namespace"
abbr --add kgingwsln "kubecolor get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "kubecolor get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "kubecolor get secret --watch --show-labels --namespace"
abbr --add kgslwowiden "kubecolor get --show-labels --watch -o=wide --namespace"
abbr --add kgposlwowiden "kubecolor get pods --show-labels --watch -o=wide --namespace"
abbr --add kgdepslwowiden "kubecolor get deployment --show-labels --watch -o=wide --namespace"
abbr --add kgstsslwowiden "kubecolor get statefulset --show-labels --watch -o=wide --namespace"
abbr --add kgsvcslwowiden "kubecolor get service --show-labels --watch -o=wide --namespace"
abbr --add kgingslwowiden "kubecolor get ingress --show-labels --watch -o=wide --namespace"
abbr --add kgcmslwowiden "kubecolor get configmap --show-labels --watch -o=wide --namespace"
abbr --add kgsecslwowiden "kubecolor get secret --show-labels --watch -o=wide --namespace"
abbr --add kgwowidesln "kubecolor get --watch -o=wide --show-labels --namespace"
abbr --add kgpowowidesln "kubecolor get pods --watch -o=wide --show-labels --namespace"
abbr --add kgdepwowidesln "kubecolor get deployment --watch -o=wide --show-labels --namespace"
abbr --add kgstswowidesln "kubecolor get statefulset --watch -o=wide --show-labels --namespace"
abbr --add kgsvcwowidesln "kubecolor get service --watch -o=wide --show-labels --namespace"
abbr --add kgingwowidesln "kubecolor get ingress --watch -o=wide --show-labels --namespace"
abbr --add kgcmwowidesln "kubecolor get configmap --watch -o=wide --show-labels --namespace"
abbr --add kgsecwowidesln "kubecolor get secret --watch -o=wide --show-labels --namespace"
abbr --add kgwslowiden "kubecolor get --watch --show-labels -o=wide --namespace"
abbr --add kgpowslowiden "kubecolor get pods --watch --show-labels -o=wide --namespace"
abbr --add kgdepwslowiden "kubecolor get deployment --watch --show-labels -o=wide --namespace"
abbr --add kgstswslowiden "kubecolor get statefulset --watch --show-labels -o=wide --namespace"
abbr --add kgsvcwslowiden "kubecolor get service --watch --show-labels -o=wide --namespace"
abbr --add kgingwslowiden "kubecolor get ingress --watch --show-labels -o=wide --namespace"
abbr --add kgcmwslowiden "kubecolor get configmap --watch --show-labels -o=wide --namespace"
abbr --add kgsecwslowiden "kubecolor get secret --watch --show-labels -o=wide --namespace"
